// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/entities/chat/chat_model.dart';
import 'core/entities/contact-request/contact_request_model.dart';
import 'core/entities/contact/contact_model.dart';
import 'core/entities/message/message_model.dart';
import 'core/entities/profile/profile_model.dart';
import 'core/entities/settings/settings_model.dart';
import 'core/offline/action_queue/action_queue_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 7487111806360095820),
      name: 'ActionQueue',
      lastPropertyId: const obx_int.IdUid(6, 4754212375464421841),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8239763993323197381),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 690479852803398016),
            name: 'channel',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(1, 2367665306712672765)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 483958376259245357),
            name: 'type',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(2, 4598511463896116981)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7050138920754006587),
            name: 'payload',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7312930574812592345),
            name: 'createdAtMSE',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(3, 4604200442593361385)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4754212375464421841),
            name: 'isHttp',
            type: 1,
            flags: 8,
            indexId: const obx_int.IdUid(4, 2614295064311538260))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 4934236275453594928),
      name: 'Chat',
      lastPropertyId: const obx_int.IdUid(13, 2068263901901510012),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6486707834580304457),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 656111012043342354),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(5, 5803319743859834340)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4606661306709619937),
            name: 'messageLongevitySeconds',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2029482861924784145),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 9170616575184317232),
            name: 'isOneToOne',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8930679822022987204),
            name: 'lastMessageTime',
            type: 10,
            flags: 8,
            indexId: const obx_int.IdUid(6, 7287894361137119830)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 201237813563152278),
            name: 'dbParticipants',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 2068263901901510012),
            name: 'dbAvatar',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'messages', srcEntity: 'Message', srcField: 'chat')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 7148624292586029034),
      name: 'Contact',
      lastPropertyId: const obx_int.IdUid(10, 7238459386756531859),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1247578593209639621),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6833401543929471773),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(7, 6512763104715792486)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8844021827370748834),
            name: 'contactPersonUid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(8, 5028288654426969847)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 193509392944045675),
            name: 'isFavorite',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7762219272507949255),
            name: 'dbEmail',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2918173606827731348),
            name: 'dbName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 7238459386756531859),
            name: 'dbAvatar',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 6760790405012068576),
      name: 'ContactRequest',
      lastPropertyId: const obx_int.IdUid(9, 2817621961955455994),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5037324725429711374),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8947553945876478858),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(9, 3331959130986894236)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5212761415579411406),
            name: 'authorId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8049173938413990109),
            name: 'timeSent',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2105300816109284026),
            name: 'queueId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8678275304045222073),
            name: 'unread',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2899439410822472811),
            name: 'dbAuthorEmail',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5748556791059750445),
            name: 'dbRecipientEmail',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2817621961955455994),
            name: 'dbMessage',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 381058101701020443),
      name: 'Message',
      lastPropertyId: const obx_int.IdUid(29, 1208494306677667935),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3952563326947658844),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8662750028911330852),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(10, 4040468722249693246)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 9212520839608594301),
            name: 'authorId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 9153146802384130062),
            name: 'text',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4601824737137532922),
            name: 'iv',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2353089289933740830),
            name: 'mac',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1108318621376269907),
            name: 'messageType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3044645396781897445),
            name: 'isEncrypted',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 807929896576633867),
            name: 'error',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 1497640284054738262),
            name: 'createdAtMSE',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(11, 7304875084129610887)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 1422397920563944577),
            name: 'chatUid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(12, 4138430278846091102)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 8330516458240674433),
            name: 'uniqueId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(13, 3010882102138979692)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 5954424922960054149),
            name: 'queueId',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(14, 3415797849604489796)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 5713832454761188830),
            name: 'successfullySent',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 462558363230263634),
            name: 'couldNotSend',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 6497439646944604993),
            name: 'pinnedByUid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 3745722604837756605),
            name: 'pinLabel',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 6701595478137728348),
            name: 'localPinLabel',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 3433434423123337237),
            name: 'playbackDurationMicroSeconds',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 6904491804263907457),
            name: 'durationIV',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 3907965061856847723),
            name: 'durationMAC',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 5370432915039729472),
            name: 'waveData',
            type: 29,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(23, 6775449061246249269),
            name: 'waveDataIV',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(24, 479224839574502712),
            name: 'waveDataMAC',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(25, 1484385213805686655),
            name: 'filepath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(26, 2351030150897239413),
            name: 'chatId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(15, 3591098884062730065),
            relationTarget: 'Chat'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(27, 7083915981674476184),
            name: 'withBaseKey',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(28, 3552863372735818277),
            name: 'fileKey',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(29, 1208494306677667935),
            name: 'dbAdditionalData',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 1841315404041682912),
      name: 'Profile',
      lastPropertyId: const obx_int.IdUid(14, 7624455643477313473),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1399551549574408378),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8970355402467754909),
            name: 'uid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5295812081720355906),
            name: 'emailVerified',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4562658611018631840),
            name: 'dbEmail',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4680063880309910063),
            name: 'dbName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 1120451617613894506),
            name: 'dbSubscription',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 2734670102412569722),
            name: 'dbAvatar',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 3980157371704576229),
            name: 'activatedForLife',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 1013626265731542308),
            name: 'activationTokenQuantity',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 7624455643477313473),
            name: 'dbAccountSettings',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 1770994479129291013),
      name: 'Settings',
      lastPropertyId: const obx_int.IdUid(2, 3843061746337845170),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1332595293146249919),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3843061746337845170),
            name: 'dbAvailableKeyboards',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(7, 1770994479129291013),
      lastIndexId: const obx_int.IdUid(15, 3591098884062730065),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        6734011593400551567,
        7993653510705270865,
        4257462892048941265,
        3830611589558590494,
        1058202039493849258,
        4793705789827528373,
        3770371504673206710,
        3556369180048710603,
        8177402884606386942,
        2127959347323040075,
        4218787220005735299,
        1648743164420436572
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ActionQueue: obx_int.EntityDefinition<ActionQueue>(
        model: _entities[0],
        toOneRelations: (ActionQueue object) => [],
        toManyRelations: (ActionQueue object) => {},
        getId: (ActionQueue object) => object.id,
        setId: (ActionQueue object, int id) {
          object.id = id;
        },
        objectToFB: (ActionQueue object, fb.Builder fbb) {
          final channelOffset = fbb.writeString(object.channel);
          final typeOffset = fbb.writeString(object.type);
          final payloadOffset = fbb.writeString(object.payload);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, channelOffset);
          fbb.addOffset(2, typeOffset);
          fbb.addOffset(3, payloadOffset);
          fbb.addInt64(4, object.createdAtMSE);
          fbb.addBool(5, object.isHttp);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final isHttpParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final channelParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final payloadParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final createdAtMSEParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = ActionQueue(
              isHttp: isHttpParam,
              type: typeParam,
              channel: channelParam,
              payload: payloadParam,
              createdAtMSE: createdAtMSEParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    Chat: obx_int.EntityDefinition<Chat>(
        model: _entities[1],
        toOneRelations: (Chat object) => [],
        toManyRelations: (Chat object) => {
              obx_int.RelInfo<Message>.toOneBacklink(
                      26, object.id, (Message srcObject) => srcObject.chat):
                  object.messages
            },
        getId: (Chat object) => object.id,
        setId: (Chat object, int id) {
          object.id = id;
        },
        objectToFB: (Chat object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final dbParticipantsOffset = object.dbParticipants == null
              ? null
              : fbb.writeString(object.dbParticipants!);
          final dbAvatarOffset = object.dbAvatar == null
              ? null
              : fbb.writeString(object.dbAvatar!);
          fbb.startTable(14);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addInt64(2, object.messageLongevitySeconds);
          fbb.addOffset(3, nameOffset);
          fbb.addBool(4, object.isOneToOne);
          fbb.addInt64(5, object.lastMessageTime?.millisecondsSinceEpoch);
          fbb.addOffset(11, dbParticipantsOffset);
          fbb.addOffset(12, dbAvatarOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastMessageTimeValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final isOneToOneParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final messageLongevitySecondsParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final lastMessageTimeParam = lastMessageTimeValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastMessageTimeValue);
          final object = Chat(
              isOneToOne: isOneToOneParam,
              uid: uidParam,
              messageLongevitySeconds: messageLongevitySecondsParam,
              name: nameParam,
              lastMessageTime: lastMessageTimeParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..dbParticipants = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 26)
            ..dbAvatar = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 28);
          obx_int.InternalToManyAccess.setRelInfo<Chat>(
              object.messages,
              store,
              obx_int.RelInfo<Message>.toOneBacklink(
                  26, object.id, (Message srcObject) => srcObject.chat));
          return object;
        }),
    Contact: obx_int.EntityDefinition<Contact>(
        model: _entities[2],
        toOneRelations: (Contact object) => [],
        toManyRelations: (Contact object) => {},
        getId: (Contact object) => object.id,
        setId: (Contact object, int id) {
          object.id = id;
        },
        objectToFB: (Contact object, fb.Builder fbb) {
          final uidOffset =
              object.uid == null ? null : fbb.writeString(object.uid!);
          final contactPersonUidOffset = object.contactPersonUid == null
              ? null
              : fbb.writeString(object.contactPersonUid!);
          final dbEmailOffset =
              object.dbEmail == null ? null : fbb.writeString(object.dbEmail!);
          final dbNameOffset =
              object.dbName == null ? null : fbb.writeString(object.dbName!);
          final dbAvatarOffset = object.dbAvatar == null
              ? null
              : fbb.writeString(object.dbAvatar!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, contactPersonUidOffset);
          fbb.addBool(6, object.isFavorite);
          fbb.addOffset(7, dbEmailOffset);
          fbb.addOffset(8, dbNameOffset);
          fbb.addOffset(9, dbAvatarOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final contactPersonUidParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final isFavoriteParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);
          final object = Contact(
              uid: uidParam,
              contactPersonUid: contactPersonUidParam,
              isFavorite: isFavoriteParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..dbEmail = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 18)
            ..dbName = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 20)
            ..dbAvatar = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 22);

          return object;
        }),
    ContactRequest: obx_int.EntityDefinition<ContactRequest>(
        model: _entities[3],
        toOneRelations: (ContactRequest object) => [],
        toManyRelations: (ContactRequest object) => {},
        getId: (ContactRequest object) => object.id,
        setId: (ContactRequest object, int id) {
          object.id = id;
        },
        objectToFB: (ContactRequest object, fb.Builder fbb) {
          final uidOffset =
              object.uid == null ? null : fbb.writeString(object.uid!);
          final authorIdOffset = object.authorId == null
              ? null
              : fbb.writeString(object.authorId!);
          final dbAuthorEmailOffset = object.dbAuthorEmail == null
              ? null
              : fbb.writeString(object.dbAuthorEmail!);
          final dbRecipientEmailOffset = object.dbRecipientEmail == null
              ? null
              : fbb.writeString(object.dbRecipientEmail!);
          final dbMessageOffset = object.dbMessage == null
              ? null
              : fbb.writeString(object.dbMessage!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, authorIdOffset);
          fbb.addInt64(3, object.timeSent?.millisecondsSinceEpoch);
          fbb.addInt64(4, object.queueId);
          fbb.addBool(5, object.unread);
          fbb.addOffset(6, dbAuthorEmailOffset);
          fbb.addOffset(7, dbRecipientEmailOffset);
          fbb.addOffset(8, dbMessageOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final timeSentValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final authorIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final timeSentParam = timeSentValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(timeSentValue);
          final queueIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final unreadParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 14);
          final object = ContactRequest(
              uid: uidParam,
              authorId: authorIdParam,
              timeSent: timeSentParam,
              queueId: queueIdParam,
              unread: unreadParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..dbAuthorEmail = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 16)
            ..dbRecipientEmail = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 18)
            ..dbMessage = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 20);

          return object;
        }),
    Message: obx_int.EntityDefinition<Message>(
        model: _entities[4],
        toOneRelations: (Message object) => [object.chat],
        toManyRelations: (Message object) => {},
        getId: (Message object) => object.id,
        setId: (Message object, int id) {
          object.id = id;
        },
        objectToFB: (Message object, fb.Builder fbb) {
          final uidOffset =
              object.uid == null ? null : fbb.writeString(object.uid!);
          final authorIdOffset = fbb.writeString(object.authorId);
          final textOffset =
              object.text == null ? null : fbb.writeString(object.text!);
          final ivOffset =
              object.iv == null ? null : fbb.writeString(object.iv!);
          final macOffset =
              object.mac == null ? null : fbb.writeString(object.mac!);
          final messageTypeOffset = fbb.writeString(object.messageType);
          final errorOffset =
              object.error == null ? null : fbb.writeString(object.error!);
          final chatUidOffset = fbb.writeString(object.chatUid);
          final uniqueIdOffset = object.uniqueId == null
              ? null
              : fbb.writeString(object.uniqueId!);
          final pinnedByUidOffset = object.pinnedByUid == null
              ? null
              : fbb.writeString(object.pinnedByUid!);
          final pinLabelOffset = object.pinLabel == null
              ? null
              : fbb.writeString(object.pinLabel!);
          final localPinLabelOffset = object.localPinLabel == null
              ? null
              : fbb.writeString(object.localPinLabel!);
          final playbackDurationMicroSecondsOffset =
              object.playbackDurationMicroSeconds == null
                  ? null
                  : fbb.writeString(object.playbackDurationMicroSeconds!);
          final durationIVOffset = object.durationIV == null
              ? null
              : fbb.writeString(object.durationIV!);
          final durationMACOffset = object.durationMAC == null
              ? null
              : fbb.writeString(object.durationMAC!);
          final waveDataOffset = object.waveData == null
              ? null
              : fbb.writeListFloat64(object.waveData!);
          final waveDataIVOffset = object.waveDataIV == null
              ? null
              : fbb.writeString(object.waveDataIV!);
          final waveDataMACOffset = object.waveDataMAC == null
              ? null
              : fbb.writeString(object.waveDataMAC!);
          final filepathOffset = object.filepath == null
              ? null
              : fbb.writeString(object.filepath!);
          final fileKeyOffset =
              object.fileKey == null ? null : fbb.writeString(object.fileKey!);
          final dbAdditionalDataOffset = object.dbAdditionalData == null
              ? null
              : fbb.writeString(object.dbAdditionalData!);
          fbb.startTable(30);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, authorIdOffset);
          fbb.addOffset(3, textOffset);
          fbb.addOffset(4, ivOffset);
          fbb.addOffset(5, macOffset);
          fbb.addOffset(6, messageTypeOffset);
          fbb.addBool(7, object.isEncrypted);
          fbb.addOffset(8, errorOffset);
          fbb.addInt64(9, object.createdAtMSE);
          fbb.addOffset(10, chatUidOffset);
          fbb.addOffset(11, uniqueIdOffset);
          fbb.addInt64(12, object.queueId);
          fbb.addBool(13, object.successfullySent);
          fbb.addBool(14, object.couldNotSend);
          fbb.addOffset(15, pinnedByUidOffset);
          fbb.addOffset(16, pinLabelOffset);
          fbb.addOffset(17, localPinLabelOffset);
          fbb.addOffset(18, playbackDurationMicroSecondsOffset);
          fbb.addOffset(19, durationIVOffset);
          fbb.addOffset(20, durationMACOffset);
          fbb.addOffset(21, waveDataOffset);
          fbb.addOffset(22, waveDataIVOffset);
          fbb.addOffset(23, waveDataMACOffset);
          fbb.addOffset(24, filepathOffset);
          fbb.addInt64(25, object.chat.targetId);
          fbb.addBool(26, object.withBaseKey);
          fbb.addOffset(27, fileKeyOffset);
          fbb.addOffset(28, dbAdditionalDataOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final authorIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final textParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final messageTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, '');
          final createdAtMSEParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final ivParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final macParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final isEncryptedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 18, false);
          final chatUidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 24, '');
          final uniqueIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 26);
          final successfullySentParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 30, false);
          final couldNotSendParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 32, false);
          final queueIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 28);
          final pinnedByUidParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 34);
          final pinLabelParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 36);
          final localPinLabelParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 38);
          final playbackDurationMicroSecondsParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 40);
          final durationIVParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 42);
          final durationMACParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 44);
          final waveDataParam =
              const fb.ListReader<double>(fb.Float64Reader(), lazy: false)
                  .vTableGetNullable(buffer, rootOffset, 46);
          final waveDataIVParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 48);
          final waveDataMACParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 50);
          final filepathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 52);
          final errorParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final withBaseKeyParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 56);
          final fileKeyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 58);
          final object = Message(
              uid: uidParam,
              authorId: authorIdParam,
              text: textParam,
              messageType: messageTypeParam,
              createdAtMSE: createdAtMSEParam,
              iv: ivParam,
              mac: macParam,
              isEncrypted: isEncryptedParam,
              chatUid: chatUidParam,
              uniqueId: uniqueIdParam,
              successfullySent: successfullySentParam,
              couldNotSend: couldNotSendParam,
              queueId: queueIdParam,
              pinnedByUid: pinnedByUidParam,
              pinLabel: pinLabelParam,
              localPinLabel: localPinLabelParam,
              playbackDurationMicroSeconds: playbackDurationMicroSecondsParam,
              durationIV: durationIVParam,
              durationMAC: durationMACParam,
              waveData: waveDataParam,
              waveDataIV: waveDataIVParam,
              waveDataMAC: waveDataMACParam,
              filepath: filepathParam,
              error: errorParam,
              withBaseKey: withBaseKeyParam,
              fileKey: fileKeyParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..dbAdditionalData = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 60);
          object.chat.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 54, 0);
          object.chat.attach(store);
          return object;
        }),
    Profile: obx_int.EntityDefinition<Profile>(
        model: _entities[5],
        toOneRelations: (Profile object) => [],
        toManyRelations: (Profile object) => {},
        getId: (Profile object) => object.id,
        setId: (Profile object, int id) {
          object.id = id;
        },
        objectToFB: (Profile object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final dbEmailOffset =
              object.dbEmail == null ? null : fbb.writeString(object.dbEmail!);
          final dbNameOffset =
              object.dbName == null ? null : fbb.writeString(object.dbName!);
          final dbSubscriptionOffset = object.dbSubscription == null
              ? null
              : fbb.writeString(object.dbSubscription!);
          final dbAvatarOffset = object.dbAvatar == null
              ? null
              : fbb.writeString(object.dbAvatar!);
          final dbAccountSettingsOffset = object.dbAccountSettings == null
              ? null
              : fbb.writeString(object.dbAccountSettings!);
          fbb.startTable(15);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addBool(2, object.emailVerified);
          fbb.addOffset(6, dbEmailOffset);
          fbb.addOffset(7, dbNameOffset);
          fbb.addOffset(9, dbSubscriptionOffset);
          fbb.addOffset(10, dbAvatarOffset);
          fbb.addBool(11, object.activatedForLife);
          fbb.addInt64(12, object.activationTokenQuantity);
          fbb.addOffset(13, dbAccountSettingsOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final emailVerifiedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final activatedForLifeParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 26, false);
          final activationTokenQuantityParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0);
          final object = Profile(
              uid: uidParam,
              emailVerified: emailVerifiedParam,
              activatedForLife: activatedForLifeParam,
              activationTokenQuantity: activationTokenQuantityParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..dbEmail = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 16)
            ..dbName = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 18)
            ..dbSubscription = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 22)
            ..dbAvatar = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 24)
            ..dbAccountSettings = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 30);

          return object;
        }),
    Settings: obx_int.EntityDefinition<Settings>(
        model: _entities[6],
        toOneRelations: (Settings object) => [],
        toManyRelations: (Settings object) => {},
        getId: (Settings object) => object.id,
        setId: (Settings object, int id) {
          object.id = id;
        },
        objectToFB: (Settings object, fb.Builder fbb) {
          final dbAvailableKeyboardsOffset = object.dbAvailableKeyboards == null
              ? null
              : fbb.writeString(object.dbAvailableKeyboards!);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, dbAvailableKeyboardsOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Settings()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..dbAvailableKeyboards =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGetNullable(buffer, rootOffset, 6);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ActionQueue] entity fields to define ObjectBox queries.
class ActionQueue_ {
  /// See [ActionQueue.id].
  static final id =
      obx.QueryIntegerProperty<ActionQueue>(_entities[0].properties[0]);

  /// See [ActionQueue.channel].
  static final channel =
      obx.QueryStringProperty<ActionQueue>(_entities[0].properties[1]);

  /// See [ActionQueue.type].
  static final type =
      obx.QueryStringProperty<ActionQueue>(_entities[0].properties[2]);

  /// See [ActionQueue.payload].
  static final payload =
      obx.QueryStringProperty<ActionQueue>(_entities[0].properties[3]);

  /// See [ActionQueue.createdAtMSE].
  static final createdAtMSE =
      obx.QueryIntegerProperty<ActionQueue>(_entities[0].properties[4]);

  /// See [ActionQueue.isHttp].
  static final isHttp =
      obx.QueryBooleanProperty<ActionQueue>(_entities[0].properties[5]);
}

/// [Chat] entity fields to define ObjectBox queries.
class Chat_ {
  /// See [Chat.id].
  static final id = obx.QueryIntegerProperty<Chat>(_entities[1].properties[0]);

  /// See [Chat.uid].
  static final uid = obx.QueryStringProperty<Chat>(_entities[1].properties[1]);

  /// See [Chat.messageLongevitySeconds].
  static final messageLongevitySeconds =
      obx.QueryIntegerProperty<Chat>(_entities[1].properties[2]);

  /// See [Chat.name].
  static final name = obx.QueryStringProperty<Chat>(_entities[1].properties[3]);

  /// See [Chat.isOneToOne].
  static final isOneToOne =
      obx.QueryBooleanProperty<Chat>(_entities[1].properties[4]);

  /// See [Chat.lastMessageTime].
  static final lastMessageTime =
      obx.QueryDateProperty<Chat>(_entities[1].properties[5]);

  /// See [Chat.dbParticipants].
  static final dbParticipants =
      obx.QueryStringProperty<Chat>(_entities[1].properties[6]);

  /// See [Chat.dbAvatar].
  static final dbAvatar =
      obx.QueryStringProperty<Chat>(_entities[1].properties[7]);

  /// see [Chat.messages]
  static final messages = obx.QueryBacklinkToMany<Message, Chat>(Message_.chat);
}

/// [Contact] entity fields to define ObjectBox queries.
class Contact_ {
  /// See [Contact.id].
  static final id =
      obx.QueryIntegerProperty<Contact>(_entities[2].properties[0]);

  /// See [Contact.uid].
  static final uid =
      obx.QueryStringProperty<Contact>(_entities[2].properties[1]);

  /// See [Contact.contactPersonUid].
  static final contactPersonUid =
      obx.QueryStringProperty<Contact>(_entities[2].properties[2]);

  /// See [Contact.isFavorite].
  static final isFavorite =
      obx.QueryBooleanProperty<Contact>(_entities[2].properties[3]);

  /// See [Contact.dbEmail].
  static final dbEmail =
      obx.QueryStringProperty<Contact>(_entities[2].properties[4]);

  /// See [Contact.dbName].
  static final dbName =
      obx.QueryStringProperty<Contact>(_entities[2].properties[5]);

  /// See [Contact.dbAvatar].
  static final dbAvatar =
      obx.QueryStringProperty<Contact>(_entities[2].properties[6]);
}

/// [ContactRequest] entity fields to define ObjectBox queries.
class ContactRequest_ {
  /// See [ContactRequest.id].
  static final id =
      obx.QueryIntegerProperty<ContactRequest>(_entities[3].properties[0]);

  /// See [ContactRequest.uid].
  static final uid =
      obx.QueryStringProperty<ContactRequest>(_entities[3].properties[1]);

  /// See [ContactRequest.authorId].
  static final authorId =
      obx.QueryStringProperty<ContactRequest>(_entities[3].properties[2]);

  /// See [ContactRequest.timeSent].
  static final timeSent =
      obx.QueryDateProperty<ContactRequest>(_entities[3].properties[3]);

  /// See [ContactRequest.queueId].
  static final queueId =
      obx.QueryIntegerProperty<ContactRequest>(_entities[3].properties[4]);

  /// See [ContactRequest.unread].
  static final unread =
      obx.QueryBooleanProperty<ContactRequest>(_entities[3].properties[5]);

  /// See [ContactRequest.dbAuthorEmail].
  static final dbAuthorEmail =
      obx.QueryStringProperty<ContactRequest>(_entities[3].properties[6]);

  /// See [ContactRequest.dbRecipientEmail].
  static final dbRecipientEmail =
      obx.QueryStringProperty<ContactRequest>(_entities[3].properties[7]);

  /// See [ContactRequest.dbMessage].
  static final dbMessage =
      obx.QueryStringProperty<ContactRequest>(_entities[3].properties[8]);
}

/// [Message] entity fields to define ObjectBox queries.
class Message_ {
  /// See [Message.id].
  static final id =
      obx.QueryIntegerProperty<Message>(_entities[4].properties[0]);

  /// See [Message.uid].
  static final uid =
      obx.QueryStringProperty<Message>(_entities[4].properties[1]);

  /// See [Message.authorId].
  static final authorId =
      obx.QueryStringProperty<Message>(_entities[4].properties[2]);

  /// See [Message.text].
  static final text =
      obx.QueryStringProperty<Message>(_entities[4].properties[3]);

  /// See [Message.iv].
  static final iv =
      obx.QueryStringProperty<Message>(_entities[4].properties[4]);

  /// See [Message.mac].
  static final mac =
      obx.QueryStringProperty<Message>(_entities[4].properties[5]);

  /// See [Message.messageType].
  static final messageType =
      obx.QueryStringProperty<Message>(_entities[4].properties[6]);

  /// See [Message.isEncrypted].
  static final isEncrypted =
      obx.QueryBooleanProperty<Message>(_entities[4].properties[7]);

  /// See [Message.error].
  static final error =
      obx.QueryStringProperty<Message>(_entities[4].properties[8]);

  /// See [Message.createdAtMSE].
  static final createdAtMSE =
      obx.QueryIntegerProperty<Message>(_entities[4].properties[9]);

  /// See [Message.chatUid].
  static final chatUid =
      obx.QueryStringProperty<Message>(_entities[4].properties[10]);

  /// See [Message.uniqueId].
  static final uniqueId =
      obx.QueryStringProperty<Message>(_entities[4].properties[11]);

  /// See [Message.queueId].
  static final queueId =
      obx.QueryIntegerProperty<Message>(_entities[4].properties[12]);

  /// See [Message.successfullySent].
  static final successfullySent =
      obx.QueryBooleanProperty<Message>(_entities[4].properties[13]);

  /// See [Message.couldNotSend].
  static final couldNotSend =
      obx.QueryBooleanProperty<Message>(_entities[4].properties[14]);

  /// See [Message.pinnedByUid].
  static final pinnedByUid =
      obx.QueryStringProperty<Message>(_entities[4].properties[15]);

  /// See [Message.pinLabel].
  static final pinLabel =
      obx.QueryStringProperty<Message>(_entities[4].properties[16]);

  /// See [Message.localPinLabel].
  static final localPinLabel =
      obx.QueryStringProperty<Message>(_entities[4].properties[17]);

  /// See [Message.playbackDurationMicroSeconds].
  static final playbackDurationMicroSeconds =
      obx.QueryStringProperty<Message>(_entities[4].properties[18]);

  /// See [Message.durationIV].
  static final durationIV =
      obx.QueryStringProperty<Message>(_entities[4].properties[19]);

  /// See [Message.durationMAC].
  static final durationMAC =
      obx.QueryStringProperty<Message>(_entities[4].properties[20]);

  /// See [Message.waveData].
  static final waveData =
      obx.QueryDoubleVectorProperty<Message>(_entities[4].properties[21]);

  /// See [Message.waveDataIV].
  static final waveDataIV =
      obx.QueryStringProperty<Message>(_entities[4].properties[22]);

  /// See [Message.waveDataMAC].
  static final waveDataMAC =
      obx.QueryStringProperty<Message>(_entities[4].properties[23]);

  /// See [Message.filepath].
  static final filepath =
      obx.QueryStringProperty<Message>(_entities[4].properties[24]);

  /// See [Message.chat].
  static final chat =
      obx.QueryRelationToOne<Message, Chat>(_entities[4].properties[25]);

  /// See [Message.withBaseKey].
  static final withBaseKey =
      obx.QueryBooleanProperty<Message>(_entities[4].properties[26]);

  /// See [Message.fileKey].
  static final fileKey =
      obx.QueryStringProperty<Message>(_entities[4].properties[27]);

  /// See [Message.dbAdditionalData].
  static final dbAdditionalData =
      obx.QueryStringProperty<Message>(_entities[4].properties[28]);
}

/// [Profile] entity fields to define ObjectBox queries.
class Profile_ {
  /// See [Profile.id].
  static final id =
      obx.QueryIntegerProperty<Profile>(_entities[5].properties[0]);

  /// See [Profile.uid].
  static final uid =
      obx.QueryStringProperty<Profile>(_entities[5].properties[1]);

  /// See [Profile.emailVerified].
  static final emailVerified =
      obx.QueryBooleanProperty<Profile>(_entities[5].properties[2]);

  /// See [Profile.dbEmail].
  static final dbEmail =
      obx.QueryStringProperty<Profile>(_entities[5].properties[3]);

  /// See [Profile.dbName].
  static final dbName =
      obx.QueryStringProperty<Profile>(_entities[5].properties[4]);

  /// See [Profile.dbSubscription].
  static final dbSubscription =
      obx.QueryStringProperty<Profile>(_entities[5].properties[5]);

  /// See [Profile.dbAvatar].
  static final dbAvatar =
      obx.QueryStringProperty<Profile>(_entities[5].properties[6]);

  /// See [Profile.activatedForLife].
  static final activatedForLife =
      obx.QueryBooleanProperty<Profile>(_entities[5].properties[7]);

  /// See [Profile.activationTokenQuantity].
  static final activationTokenQuantity =
      obx.QueryIntegerProperty<Profile>(_entities[5].properties[8]);

  /// See [Profile.dbAccountSettings].
  static final dbAccountSettings =
      obx.QueryStringProperty<Profile>(_entities[5].properties[9]);
}

/// [Settings] entity fields to define ObjectBox queries.
class Settings_ {
  /// See [Settings.id].
  static final id =
      obx.QueryIntegerProperty<Settings>(_entities[6].properties[0]);

  /// See [Settings.dbAvailableKeyboards].
  static final dbAvailableKeyboards =
      obx.QueryStringProperty<Settings>(_entities[6].properties[1]);
}
