// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/entities/chat/chat_model.dart';
import 'core/entities/chat/participant_model.dart';
import 'core/entities/contact-request/contact_request_model.dart';
import 'core/entities/contact/contact_model.dart';
import 'core/entities/message/message_model.dart';
import 'core/entities/profile/profile_model.dart';
import 'core/offline/action_queue/action_queue_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 372937194368687323),
      name: 'Chat',
      lastPropertyId: const obx_int.IdUid(11, 3257620050611006191),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 496066587075907108),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1797603169474254040),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 7417568637899194392)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1796389544038958094),
            name: 'messageLongevitySeconds',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2224808748892177155),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3639087631448733413),
            name: 'isOneToOne',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7848993481254013620),
            name: 'lastMessageTime',
            type: 10,
            flags: 8,
            indexId: const obx_int.IdUid(2, 7828957042644059983)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6446550641835797971),
            name: 'syncRequired',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6509457711126745653),
            name: 'syncTime',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7132724385097852729),
            name: 'avatarColor',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4960301968854219286),
            name: 'avatarIcon',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 3257620050611006191),
            name: 'avatarPic',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'participants', srcEntity: 'Participant', srcField: 'chat'),
        obx_int.ModelBacklink(
            name: 'messages', srcEntity: 'Message', srcField: 'chat')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 8395604750634349924),
      name: 'Participant',
      lastPropertyId: const obx_int.IdUid(13, 2538485000514319932),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3140738347883873507),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7306573019829737168),
            name: 'uid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5157245019723225303),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7222374184870975437),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2758979418291972671),
            name: 'lastSawChat',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1310858162911504798),
            name: 'isCreator',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2403685613991470062),
            name: 'isAdmin',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8946033037738850628),
            name: 'pubKey',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7411497473296940744),
            name: 'gotPubKey',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 237801397465781866),
            name: 'chatId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 5562927964059586425),
            relationTarget: 'Chat'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 5610687627734890430),
            name: 'avatarColor',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 4281053167053723617),
            name: 'avatarIcon',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 2538485000514319932),
            name: 'avatarPic',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 174085889404853842),
      name: 'ActionQueue',
      lastPropertyId: const obx_int.IdUid(6, 1207935701358571007),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3878610403772081266),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 518932676002101658),
            name: 'channel',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(4, 4858392141036813653)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5899978974047599556),
            name: 'type',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(5, 4631410448222255127)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4734700568557422587),
            name: 'payload',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6861900140166326899),
            name: 'createdAtMSE',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(6, 966174557015596344)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1207935701358571007),
            name: 'isHttp',
            type: 1,
            flags: 8,
            indexId: const obx_int.IdUid(7, 2788847655698301832))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 3256006726252938619),
      name: 'Contact',
      lastPropertyId: const obx_int.IdUid(9, 3254574943619528517),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3835001356443603724),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4363879514860275686),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(8, 8283532152140517817)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3925708090378952839),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 195948196470593874),
            name: 'contactPersonUid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(9, 2298344643898579565)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5844032266063413579),
            name: 'avatarColor',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6141076677251091088),
            name: 'avatarIcon',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5835449303478586129),
            name: 'avatarPic',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 9208670894667018502),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3254574943619528517),
            name: 'isFavorite',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 1055908107619857269),
      name: 'ContactRequest',
      lastPropertyId: const obx_int.IdUid(9, 3115437306457613564),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6791634532749002900),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3276126211965268815),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(10, 7726567333746624721)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1935783775396277350),
            name: 'authorId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 572032084140616956),
            name: 'authorEmail',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4835332164262847696),
            name: 'recipientEmail',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8315176908039517271),
            name: 'message',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7096519126674163652),
            name: 'timeSent',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7307497832114457014),
            name: 'queueId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3115437306457613564),
            name: 'unread',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 7715411867423381034),
      name: 'Message',
      lastPropertyId: const obx_int.IdUid(26, 1292397910085762565),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6193219001936189086),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3205564614717453819),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(11, 743172683645461739)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 9016633602216037609),
            name: 'authorId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3764813623545403712),
            name: 'text',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3382277886679507558),
            name: 'iv',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 788932041372978895),
            name: 'mac',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6418039618855054199),
            name: 'messageType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8549032723976726060),
            name: 'isEncrypted',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 1490993974120651898),
            name: 'error',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6667188206186250816),
            name: 'createdAtMSE',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(12, 6637692378027186109)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 3461459293206068546),
            name: 'chatUid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(13, 6483001927584970615)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 664550285312468086),
            name: 'uniqueId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(14, 3773916419867091184)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 4553521238696558945),
            name: 'queueId',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(15, 8830306294288428295)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 2531272398137520313),
            name: 'successfullySent',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 7330385604614663633),
            name: 'couldNotSend',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 1916166604082151460),
            name: 'pinnedByUid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 5634263819453511024),
            name: 'pinLabel',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 391861716434374612),
            name: 'localPinLabel',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 4570918027248575059),
            name: 'playbackDurationMicroSeconds',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 6280780047733528053),
            name: 'durationIV',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 130692958726001767),
            name: 'durationMAC',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 2701256056088093950),
            name: 'waveData',
            type: 29,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(23, 6500048009962098964),
            name: 'waveDataIV',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(24, 204193618581195447),
            name: 'waveDataMAC',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(25, 7295736734398325549),
            name: 'filepath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(26, 1292397910085762565),
            name: 'chatId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(16, 6632583265886720074),
            relationTarget: 'Chat')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 6001606463237092560),
      name: 'Profile',
      lastPropertyId: const obx_int.IdUid(8, 2502079331924638241),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5240065712646817761),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1965452599062366425),
            name: 'uid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1054598126959679408),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8716255141686264958),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3163325898660752283),
            name: 'emailVerified',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2089415412449252355),
            name: 'avatarColor',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2675422248412665265),
            name: 'avatarIcon',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2502079331924638241),
            name: 'avatarPic',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(7, 6001606463237092560),
      lastIndexId: const obx_int.IdUid(16, 6632583265886720074),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Chat: obx_int.EntityDefinition<Chat>(
        model: _entities[0],
        toOneRelations: (Chat object) => [],
        toManyRelations: (Chat object) => {
              obx_int.RelInfo<Participant>.toOneBacklink(
                      10, object.id, (Participant srcObject) => srcObject.chat):
                  object.participants,
              obx_int.RelInfo<Message>.toOneBacklink(
                      26, object.id, (Message srcObject) => srcObject.chat):
                  object.messages
            },
        getId: (Chat object) => object.id,
        setId: (Chat object, int id) {
          object.id = id;
        },
        objectToFB: (Chat object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final avatarColorOffset = object.avatarColor == null
              ? null
              : fbb.writeString(object.avatarColor!);
          final avatarIconOffset = object.avatarIcon == null
              ? null
              : fbb.writeString(object.avatarIcon!);
          final avatarPicOffset = object.avatarPic == null
              ? null
              : fbb.writeString(object.avatarPic!);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addInt64(2, object.messageLongevitySeconds);
          fbb.addOffset(3, nameOffset);
          fbb.addBool(4, object.isOneToOne);
          fbb.addInt64(5, object.lastMessageTime?.millisecondsSinceEpoch);
          fbb.addBool(6, object.syncRequired);
          fbb.addInt64(7, object.syncTime);
          fbb.addOffset(8, avatarColorOffset);
          fbb.addOffset(9, avatarIconOffset);
          fbb.addOffset(10, avatarPicOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastMessageTimeValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final isOneToOneParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final messageLongevitySecondsParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final lastMessageTimeParam = lastMessageTimeValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastMessageTimeValue);
          final avatarColorParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20);
          final avatarIconParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final avatarPicParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 24);
          final syncRequiredParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 16);
          final syncTimeParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
          final object = Chat(
              isOneToOne: isOneToOneParam,
              uid: uidParam,
              messageLongevitySeconds: messageLongevitySecondsParam,
              name: nameParam,
              lastMessageTime: lastMessageTimeParam,
              avatarColor: avatarColorParam,
              avatarIcon: avatarIconParam,
              avatarPic: avatarPicParam,
              syncRequired: syncRequiredParam,
              syncTime: syncTimeParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          obx_int.InternalToManyAccess.setRelInfo<Chat>(
              object.participants,
              store,
              obx_int.RelInfo<Participant>.toOneBacklink(
                  10, object.id, (Participant srcObject) => srcObject.chat));
          obx_int.InternalToManyAccess.setRelInfo<Chat>(
              object.messages,
              store,
              obx_int.RelInfo<Message>.toOneBacklink(
                  26, object.id, (Message srcObject) => srcObject.chat));
          return object;
        }),
    Participant: obx_int.EntityDefinition<Participant>(
        model: _entities[1],
        toOneRelations: (Participant object) => [object.chat],
        toManyRelations: (Participant object) => {},
        getId: (Participant object) => object.id,
        setId: (Participant object, int id) {
          object.id = id;
        },
        objectToFB: (Participant object, fb.Builder fbb) {
          final uidOffset =
              object.uid == null ? null : fbb.writeString(object.uid!);
          final emailOffset =
              object.email == null ? null : fbb.writeString(object.email!);
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final pubKeyOffset =
              object.pubKey == null ? null : fbb.writeString(object.pubKey!);
          final avatarColorOffset = object.avatarColor == null
              ? null
              : fbb.writeString(object.avatarColor!);
          final avatarIconOffset = object.avatarIcon == null
              ? null
              : fbb.writeString(object.avatarIcon!);
          final avatarPicOffset = object.avatarPic == null
              ? null
              : fbb.writeString(object.avatarPic!);
          fbb.startTable(14);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, emailOffset);
          fbb.addOffset(3, nameOffset);
          fbb.addInt64(4, object.lastSawChat?.millisecondsSinceEpoch);
          fbb.addBool(5, object.isCreator);
          fbb.addBool(6, object.isAdmin);
          fbb.addOffset(7, pubKeyOffset);
          fbb.addBool(8, object.gotPubKey);
          fbb.addInt64(9, object.chat.targetId);
          fbb.addOffset(10, avatarColorOffset);
          fbb.addOffset(11, avatarIconOffset);
          fbb.addOffset(12, avatarPicOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastSawChatValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final lastSawChatParam = lastSawChatValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastSawChatValue);
          final avatarColorParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 24);
          final avatarIconParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 26);
          final avatarPicParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 28);
          final isCreatorParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final isAdminParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);
          final pubKeyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final gotPubKeyParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 20, false);
          final object = Participant(
              uid: uidParam,
              email: emailParam,
              name: nameParam,
              lastSawChat: lastSawChatParam,
              avatarColor: avatarColorParam,
              avatarIcon: avatarIconParam,
              avatarPic: avatarPicParam,
              isCreator: isCreatorParam,
              isAdmin: isAdminParam,
              pubKey: pubKeyParam,
              gotPubKey: gotPubKeyParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.chat.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          object.chat.attach(store);
          return object;
        }),
    ActionQueue: obx_int.EntityDefinition<ActionQueue>(
        model: _entities[2],
        toOneRelations: (ActionQueue object) => [],
        toManyRelations: (ActionQueue object) => {},
        getId: (ActionQueue object) => object.id,
        setId: (ActionQueue object, int id) {
          object.id = id;
        },
        objectToFB: (ActionQueue object, fb.Builder fbb) {
          final channelOffset = fbb.writeString(object.channel);
          final typeOffset = fbb.writeString(object.type);
          final payloadOffset = fbb.writeString(object.payload);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, channelOffset);
          fbb.addOffset(2, typeOffset);
          fbb.addOffset(3, payloadOffset);
          fbb.addInt64(4, object.createdAtMSE);
          fbb.addBool(5, object.isHttp);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final isHttpParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final channelParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final payloadParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final createdAtMSEParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = ActionQueue(
              isHttp: isHttpParam,
              type: typeParam,
              channel: channelParam,
              payload: payloadParam,
              createdAtMSE: createdAtMSEParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    Contact: obx_int.EntityDefinition<Contact>(
        model: _entities[3],
        toOneRelations: (Contact object) => [],
        toManyRelations: (Contact object) => {},
        getId: (Contact object) => object.id,
        setId: (Contact object, int id) {
          object.id = id;
        },
        objectToFB: (Contact object, fb.Builder fbb) {
          final uidOffset =
              object.uid == null ? null : fbb.writeString(object.uid!);
          final emailOffset =
              object.email == null ? null : fbb.writeString(object.email!);
          final contactPersonUidOffset = object.contactPersonUid == null
              ? null
              : fbb.writeString(object.contactPersonUid!);
          final avatarColorOffset = object.avatarColor == null
              ? null
              : fbb.writeString(object.avatarColor!);
          final avatarIconOffset = object.avatarIcon == null
              ? null
              : fbb.writeString(object.avatarIcon!);
          final avatarPicOffset = object.avatarPic == null
              ? null
              : fbb.writeString(object.avatarPic!);
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, emailOffset);
          fbb.addOffset(3, contactPersonUidOffset);
          fbb.addOffset(4, avatarColorOffset);
          fbb.addOffset(5, avatarIconOffset);
          fbb.addOffset(6, avatarPicOffset);
          fbb.addOffset(7, nameOffset);
          fbb.addBool(8, object.isFavorite);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final avatarColorParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final avatarIconParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final avatarPicParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final contactPersonUidParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final isFavoriteParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 20, false);
          final object = Contact(
              uid: uidParam,
              email: emailParam,
              avatarColor: avatarColorParam,
              avatarIcon: avatarIconParam,
              avatarPic: avatarPicParam,
              name: nameParam,
              contactPersonUid: contactPersonUidParam,
              isFavorite: isFavoriteParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    ContactRequest: obx_int.EntityDefinition<ContactRequest>(
        model: _entities[4],
        toOneRelations: (ContactRequest object) => [],
        toManyRelations: (ContactRequest object) => {},
        getId: (ContactRequest object) => object.id,
        setId: (ContactRequest object, int id) {
          object.id = id;
        },
        objectToFB: (ContactRequest object, fb.Builder fbb) {
          final uidOffset =
              object.uid == null ? null : fbb.writeString(object.uid!);
          final authorIdOffset = object.authorId == null
              ? null
              : fbb.writeString(object.authorId!);
          final authorEmailOffset = object.authorEmail == null
              ? null
              : fbb.writeString(object.authorEmail!);
          final recipientEmailOffset = object.recipientEmail == null
              ? null
              : fbb.writeString(object.recipientEmail!);
          final messageOffset =
              object.message == null ? null : fbb.writeString(object.message!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, authorIdOffset);
          fbb.addOffset(3, authorEmailOffset);
          fbb.addOffset(4, recipientEmailOffset);
          fbb.addOffset(5, messageOffset);
          fbb.addInt64(6, object.timeSent?.millisecondsSinceEpoch);
          fbb.addInt64(7, object.queueId);
          fbb.addBool(8, object.unread);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final timeSentValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final authorIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final authorEmailParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final recipientEmailParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final messageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final timeSentParam = timeSentValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(timeSentValue);
          final queueIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
          final unreadParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 20);
          final object = ContactRequest(
              uid: uidParam,
              authorId: authorIdParam,
              authorEmail: authorEmailParam,
              recipientEmail: recipientEmailParam,
              message: messageParam,
              timeSent: timeSentParam,
              queueId: queueIdParam,
              unread: unreadParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    Message: obx_int.EntityDefinition<Message>(
        model: _entities[5],
        toOneRelations: (Message object) => [object.chat],
        toManyRelations: (Message object) => {},
        getId: (Message object) => object.id,
        setId: (Message object, int id) {
          object.id = id;
        },
        objectToFB: (Message object, fb.Builder fbb) {
          final uidOffset =
              object.uid == null ? null : fbb.writeString(object.uid!);
          final authorIdOffset = fbb.writeString(object.authorId);
          final textOffset =
              object.text == null ? null : fbb.writeString(object.text!);
          final ivOffset =
              object.iv == null ? null : fbb.writeString(object.iv!);
          final macOffset =
              object.mac == null ? null : fbb.writeString(object.mac!);
          final messageTypeOffset = fbb.writeString(object.messageType);
          final errorOffset =
              object.error == null ? null : fbb.writeString(object.error!);
          final chatUidOffset = fbb.writeString(object.chatUid);
          final uniqueIdOffset = object.uniqueId == null
              ? null
              : fbb.writeString(object.uniqueId!);
          final pinnedByUidOffset = object.pinnedByUid == null
              ? null
              : fbb.writeString(object.pinnedByUid!);
          final pinLabelOffset = object.pinLabel == null
              ? null
              : fbb.writeString(object.pinLabel!);
          final localPinLabelOffset = object.localPinLabel == null
              ? null
              : fbb.writeString(object.localPinLabel!);
          final playbackDurationMicroSecondsOffset =
              object.playbackDurationMicroSeconds == null
                  ? null
                  : fbb.writeString(object.playbackDurationMicroSeconds!);
          final durationIVOffset = object.durationIV == null
              ? null
              : fbb.writeString(object.durationIV!);
          final durationMACOffset = object.durationMAC == null
              ? null
              : fbb.writeString(object.durationMAC!);
          final waveDataOffset = object.waveData == null
              ? null
              : fbb.writeListFloat64(object.waveData!);
          final waveDataIVOffset = object.waveDataIV == null
              ? null
              : fbb.writeString(object.waveDataIV!);
          final waveDataMACOffset = object.waveDataMAC == null
              ? null
              : fbb.writeString(object.waveDataMAC!);
          final filepathOffset = object.filepath == null
              ? null
              : fbb.writeString(object.filepath!);
          fbb.startTable(27);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, authorIdOffset);
          fbb.addOffset(3, textOffset);
          fbb.addOffset(4, ivOffset);
          fbb.addOffset(5, macOffset);
          fbb.addOffset(6, messageTypeOffset);
          fbb.addBool(7, object.isEncrypted);
          fbb.addOffset(8, errorOffset);
          fbb.addInt64(9, object.createdAtMSE);
          fbb.addOffset(10, chatUidOffset);
          fbb.addOffset(11, uniqueIdOffset);
          fbb.addInt64(12, object.queueId);
          fbb.addBool(13, object.successfullySent);
          fbb.addBool(14, object.couldNotSend);
          fbb.addOffset(15, pinnedByUidOffset);
          fbb.addOffset(16, pinLabelOffset);
          fbb.addOffset(17, localPinLabelOffset);
          fbb.addOffset(18, playbackDurationMicroSecondsOffset);
          fbb.addOffset(19, durationIVOffset);
          fbb.addOffset(20, durationMACOffset);
          fbb.addOffset(21, waveDataOffset);
          fbb.addOffset(22, waveDataIVOffset);
          fbb.addOffset(23, waveDataMACOffset);
          fbb.addOffset(24, filepathOffset);
          fbb.addInt64(25, object.chat.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final authorIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final textParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final messageTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, '');
          final createdAtMSEParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final ivParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final macParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final isEncryptedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 18, false);
          final chatUidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 24, '');
          final uniqueIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 26);
          final successfullySentParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 30, false);
          final couldNotSendParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 32, false);
          final queueIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 28);
          final pinnedByUidParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 34);
          final pinLabelParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 36);
          final localPinLabelParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 38);
          final playbackDurationMicroSecondsParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 40);
          final durationIVParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 42);
          final durationMACParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 44);
          final waveDataParam =
              const fb.ListReader<double>(fb.Float64Reader(), lazy: false)
                  .vTableGetNullable(buffer, rootOffset, 46);
          final waveDataIVParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 48);
          final waveDataMACParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 50);
          final filepathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 52);
          final errorParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final object = Message(
              uid: uidParam,
              authorId: authorIdParam,
              text: textParam,
              messageType: messageTypeParam,
              createdAtMSE: createdAtMSEParam,
              iv: ivParam,
              mac: macParam,
              isEncrypted: isEncryptedParam,
              chatUid: chatUidParam,
              uniqueId: uniqueIdParam,
              successfullySent: successfullySentParam,
              couldNotSend: couldNotSendParam,
              queueId: queueIdParam,
              pinnedByUid: pinnedByUidParam,
              pinLabel: pinLabelParam,
              localPinLabel: localPinLabelParam,
              playbackDurationMicroSeconds: playbackDurationMicroSecondsParam,
              durationIV: durationIVParam,
              durationMAC: durationMACParam,
              waveData: waveDataParam,
              waveDataIV: waveDataIVParam,
              waveDataMAC: waveDataMACParam,
              filepath: filepathParam,
              error: errorParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.chat.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 54, 0);
          object.chat.attach(store);
          return object;
        }),
    Profile: obx_int.EntityDefinition<Profile>(
        model: _entities[6],
        toOneRelations: (Profile object) => [],
        toManyRelations: (Profile object) => {},
        getId: (Profile object) => object.id,
        setId: (Profile object, int id) {
          object.id = id;
        },
        objectToFB: (Profile object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final emailOffset = fbb.writeString(object.email);
          final avatarColorOffset = object.avatarColor == null
              ? null
              : fbb.writeString(object.avatarColor!);
          final avatarIconOffset = object.avatarIcon == null
              ? null
              : fbb.writeString(object.avatarIcon!);
          final avatarPicOffset = object.avatarPic == null
              ? null
              : fbb.writeString(object.avatarPic!);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, emailOffset);
          fbb.addBool(4, object.emailVerified);
          fbb.addOffset(5, avatarColorOffset);
          fbb.addOffset(6, avatarIconOffset);
          fbb.addOffset(7, avatarPicOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final avatarColorParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14);
          final avatarIconParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final avatarPicParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final emailVerifiedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final object = Profile(
              uid: uidParam,
              name: nameParam,
              email: emailParam,
              avatarColor: avatarColorParam,
              avatarIcon: avatarIconParam,
              avatarPic: avatarPicParam,
              emailVerified: emailVerifiedParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Chat] entity fields to define ObjectBox queries.
class Chat_ {
  /// See [Chat.id].
  static final id = obx.QueryIntegerProperty<Chat>(_entities[0].properties[0]);

  /// See [Chat.uid].
  static final uid = obx.QueryStringProperty<Chat>(_entities[0].properties[1]);

  /// See [Chat.messageLongevitySeconds].
  static final messageLongevitySeconds =
      obx.QueryIntegerProperty<Chat>(_entities[0].properties[2]);

  /// See [Chat.name].
  static final name = obx.QueryStringProperty<Chat>(_entities[0].properties[3]);

  /// See [Chat.isOneToOne].
  static final isOneToOne =
      obx.QueryBooleanProperty<Chat>(_entities[0].properties[4]);

  /// See [Chat.lastMessageTime].
  static final lastMessageTime =
      obx.QueryDateProperty<Chat>(_entities[0].properties[5]);

  /// See [Chat.syncRequired].
  static final syncRequired =
      obx.QueryBooleanProperty<Chat>(_entities[0].properties[6]);

  /// See [Chat.syncTime].
  static final syncTime =
      obx.QueryIntegerProperty<Chat>(_entities[0].properties[7]);

  /// See [Chat.avatarColor].
  static final avatarColor =
      obx.QueryStringProperty<Chat>(_entities[0].properties[8]);

  /// See [Chat.avatarIcon].
  static final avatarIcon =
      obx.QueryStringProperty<Chat>(_entities[0].properties[9]);

  /// See [Chat.avatarPic].
  static final avatarPic =
      obx.QueryStringProperty<Chat>(_entities[0].properties[10]);

  /// see [Chat.participants]
  static final participants =
      obx.QueryBacklinkToMany<Participant, Chat>(Participant_.chat);

  /// see [Chat.messages]
  static final messages = obx.QueryBacklinkToMany<Message, Chat>(Message_.chat);
}

/// [Participant] entity fields to define ObjectBox queries.
class Participant_ {
  /// See [Participant.id].
  static final id =
      obx.QueryIntegerProperty<Participant>(_entities[1].properties[0]);

  /// See [Participant.uid].
  static final uid =
      obx.QueryStringProperty<Participant>(_entities[1].properties[1]);

  /// See [Participant.email].
  static final email =
      obx.QueryStringProperty<Participant>(_entities[1].properties[2]);

  /// See [Participant.name].
  static final name =
      obx.QueryStringProperty<Participant>(_entities[1].properties[3]);

  /// See [Participant.lastSawChat].
  static final lastSawChat =
      obx.QueryDateProperty<Participant>(_entities[1].properties[4]);

  /// See [Participant.isCreator].
  static final isCreator =
      obx.QueryBooleanProperty<Participant>(_entities[1].properties[5]);

  /// See [Participant.isAdmin].
  static final isAdmin =
      obx.QueryBooleanProperty<Participant>(_entities[1].properties[6]);

  /// See [Participant.pubKey].
  static final pubKey =
      obx.QueryStringProperty<Participant>(_entities[1].properties[7]);

  /// See [Participant.gotPubKey].
  static final gotPubKey =
      obx.QueryBooleanProperty<Participant>(_entities[1].properties[8]);

  /// See [Participant.chat].
  static final chat =
      obx.QueryRelationToOne<Participant, Chat>(_entities[1].properties[9]);

  /// See [Participant.avatarColor].
  static final avatarColor =
      obx.QueryStringProperty<Participant>(_entities[1].properties[10]);

  /// See [Participant.avatarIcon].
  static final avatarIcon =
      obx.QueryStringProperty<Participant>(_entities[1].properties[11]);

  /// See [Participant.avatarPic].
  static final avatarPic =
      obx.QueryStringProperty<Participant>(_entities[1].properties[12]);
}

/// [ActionQueue] entity fields to define ObjectBox queries.
class ActionQueue_ {
  /// See [ActionQueue.id].
  static final id =
      obx.QueryIntegerProperty<ActionQueue>(_entities[2].properties[0]);

  /// See [ActionQueue.channel].
  static final channel =
      obx.QueryStringProperty<ActionQueue>(_entities[2].properties[1]);

  /// See [ActionQueue.type].
  static final type =
      obx.QueryStringProperty<ActionQueue>(_entities[2].properties[2]);

  /// See [ActionQueue.payload].
  static final payload =
      obx.QueryStringProperty<ActionQueue>(_entities[2].properties[3]);

  /// See [ActionQueue.createdAtMSE].
  static final createdAtMSE =
      obx.QueryIntegerProperty<ActionQueue>(_entities[2].properties[4]);

  /// See [ActionQueue.isHttp].
  static final isHttp =
      obx.QueryBooleanProperty<ActionQueue>(_entities[2].properties[5]);
}

/// [Contact] entity fields to define ObjectBox queries.
class Contact_ {
  /// See [Contact.id].
  static final id =
      obx.QueryIntegerProperty<Contact>(_entities[3].properties[0]);

  /// See [Contact.uid].
  static final uid =
      obx.QueryStringProperty<Contact>(_entities[3].properties[1]);

  /// See [Contact.email].
  static final email =
      obx.QueryStringProperty<Contact>(_entities[3].properties[2]);

  /// See [Contact.contactPersonUid].
  static final contactPersonUid =
      obx.QueryStringProperty<Contact>(_entities[3].properties[3]);

  /// See [Contact.avatarColor].
  static final avatarColor =
      obx.QueryStringProperty<Contact>(_entities[3].properties[4]);

  /// See [Contact.avatarIcon].
  static final avatarIcon =
      obx.QueryStringProperty<Contact>(_entities[3].properties[5]);

  /// See [Contact.avatarPic].
  static final avatarPic =
      obx.QueryStringProperty<Contact>(_entities[3].properties[6]);

  /// See [Contact.name].
  static final name =
      obx.QueryStringProperty<Contact>(_entities[3].properties[7]);

  /// See [Contact.isFavorite].
  static final isFavorite =
      obx.QueryBooleanProperty<Contact>(_entities[3].properties[8]);
}

/// [ContactRequest] entity fields to define ObjectBox queries.
class ContactRequest_ {
  /// See [ContactRequest.id].
  static final id =
      obx.QueryIntegerProperty<ContactRequest>(_entities[4].properties[0]);

  /// See [ContactRequest.uid].
  static final uid =
      obx.QueryStringProperty<ContactRequest>(_entities[4].properties[1]);

  /// See [ContactRequest.authorId].
  static final authorId =
      obx.QueryStringProperty<ContactRequest>(_entities[4].properties[2]);

  /// See [ContactRequest.authorEmail].
  static final authorEmail =
      obx.QueryStringProperty<ContactRequest>(_entities[4].properties[3]);

  /// See [ContactRequest.recipientEmail].
  static final recipientEmail =
      obx.QueryStringProperty<ContactRequest>(_entities[4].properties[4]);

  /// See [ContactRequest.message].
  static final message =
      obx.QueryStringProperty<ContactRequest>(_entities[4].properties[5]);

  /// See [ContactRequest.timeSent].
  static final timeSent =
      obx.QueryDateProperty<ContactRequest>(_entities[4].properties[6]);

  /// See [ContactRequest.queueId].
  static final queueId =
      obx.QueryIntegerProperty<ContactRequest>(_entities[4].properties[7]);

  /// See [ContactRequest.unread].
  static final unread =
      obx.QueryBooleanProperty<ContactRequest>(_entities[4].properties[8]);
}

/// [Message] entity fields to define ObjectBox queries.
class Message_ {
  /// See [Message.id].
  static final id =
      obx.QueryIntegerProperty<Message>(_entities[5].properties[0]);

  /// See [Message.uid].
  static final uid =
      obx.QueryStringProperty<Message>(_entities[5].properties[1]);

  /// See [Message.authorId].
  static final authorId =
      obx.QueryStringProperty<Message>(_entities[5].properties[2]);

  /// See [Message.text].
  static final text =
      obx.QueryStringProperty<Message>(_entities[5].properties[3]);

  /// See [Message.iv].
  static final iv =
      obx.QueryStringProperty<Message>(_entities[5].properties[4]);

  /// See [Message.mac].
  static final mac =
      obx.QueryStringProperty<Message>(_entities[5].properties[5]);

  /// See [Message.messageType].
  static final messageType =
      obx.QueryStringProperty<Message>(_entities[5].properties[6]);

  /// See [Message.isEncrypted].
  static final isEncrypted =
      obx.QueryBooleanProperty<Message>(_entities[5].properties[7]);

  /// See [Message.error].
  static final error =
      obx.QueryStringProperty<Message>(_entities[5].properties[8]);

  /// See [Message.createdAtMSE].
  static final createdAtMSE =
      obx.QueryIntegerProperty<Message>(_entities[5].properties[9]);

  /// See [Message.chatUid].
  static final chatUid =
      obx.QueryStringProperty<Message>(_entities[5].properties[10]);

  /// See [Message.uniqueId].
  static final uniqueId =
      obx.QueryStringProperty<Message>(_entities[5].properties[11]);

  /// See [Message.queueId].
  static final queueId =
      obx.QueryIntegerProperty<Message>(_entities[5].properties[12]);

  /// See [Message.successfullySent].
  static final successfullySent =
      obx.QueryBooleanProperty<Message>(_entities[5].properties[13]);

  /// See [Message.couldNotSend].
  static final couldNotSend =
      obx.QueryBooleanProperty<Message>(_entities[5].properties[14]);

  /// See [Message.pinnedByUid].
  static final pinnedByUid =
      obx.QueryStringProperty<Message>(_entities[5].properties[15]);

  /// See [Message.pinLabel].
  static final pinLabel =
      obx.QueryStringProperty<Message>(_entities[5].properties[16]);

  /// See [Message.localPinLabel].
  static final localPinLabel =
      obx.QueryStringProperty<Message>(_entities[5].properties[17]);

  /// See [Message.playbackDurationMicroSeconds].
  static final playbackDurationMicroSeconds =
      obx.QueryStringProperty<Message>(_entities[5].properties[18]);

  /// See [Message.durationIV].
  static final durationIV =
      obx.QueryStringProperty<Message>(_entities[5].properties[19]);

  /// See [Message.durationMAC].
  static final durationMAC =
      obx.QueryStringProperty<Message>(_entities[5].properties[20]);

  /// See [Message.waveData].
  static final waveData =
      obx.QueryDoubleVectorProperty<Message>(_entities[5].properties[21]);

  /// See [Message.waveDataIV].
  static final waveDataIV =
      obx.QueryStringProperty<Message>(_entities[5].properties[22]);

  /// See [Message.waveDataMAC].
  static final waveDataMAC =
      obx.QueryStringProperty<Message>(_entities[5].properties[23]);

  /// See [Message.filepath].
  static final filepath =
      obx.QueryStringProperty<Message>(_entities[5].properties[24]);

  /// See [Message.chat].
  static final chat =
      obx.QueryRelationToOne<Message, Chat>(_entities[5].properties[25]);
}

/// [Profile] entity fields to define ObjectBox queries.
class Profile_ {
  /// See [Profile.id].
  static final id =
      obx.QueryIntegerProperty<Profile>(_entities[6].properties[0]);

  /// See [Profile.uid].
  static final uid =
      obx.QueryStringProperty<Profile>(_entities[6].properties[1]);

  /// See [Profile.name].
  static final name =
      obx.QueryStringProperty<Profile>(_entities[6].properties[2]);

  /// See [Profile.email].
  static final email =
      obx.QueryStringProperty<Profile>(_entities[6].properties[3]);

  /// See [Profile.emailVerified].
  static final emailVerified =
      obx.QueryBooleanProperty<Profile>(_entities[6].properties[4]);

  /// See [Profile.avatarColor].
  static final avatarColor =
      obx.QueryStringProperty<Profile>(_entities[6].properties[5]);

  /// See [Profile.avatarIcon].
  static final avatarIcon =
      obx.QueryStringProperty<Profile>(_entities[6].properties[6]);

  /// See [Profile.avatarPic].
  static final avatarPic =
      obx.QueryStringProperty<Profile>(_entities[6].properties[7]);
}
