import 'package:flutter/material.dart';

/// A searchable registry of Material Icons for use in the icon picker.
/// Each entry maps a human-readable name to its [IconData].
class MaterialIconRegistry {
  MaterialIconRegistry._();

  static const Map<String, IconData> icons = {
    // ── People & Social ──────────────────────────────────────────────
    'person': Icons.person,
    'person outline': Icons.person_outline,
    'person add': Icons.person_add,
    'person remove': Icons.person_remove,
    'person search': Icons.person_search,
    'person pin': Icons.person_pin,
    'person pin circle': Icons.person_pin_circle,
    'people': Icons.people,
    'people outline': Icons.people_outline,
    'group': Icons.group,
    'group add': Icons.group_add,
    'group remove': Icons.group_remove,
    'groups': Icons.groups,
    'face': Icons.face,
    'face 2': Icons.face_2,
    'face 3': Icons.face_3,
    'face 4': Icons.face_4,
    'face 5': Icons.face_5,
    'face 6': Icons.face_6,
    'emoji emotions': Icons.emoji_emotions,
    'emoji people': Icons.emoji_people,
    'emoji nature': Icons.emoji_nature,
    'emoji food beverage': Icons.emoji_food_beverage,
    'emoji objects': Icons.emoji_objects,
    'emoji symbols': Icons.emoji_symbols,
    'emoji transportation': Icons.emoji_transportation,
    'emoji flags': Icons.emoji_flags,
    'sentiment satisfied': Icons.sentiment_satisfied,
    'sentiment very satisfied': Icons.sentiment_very_satisfied,
    'sentiment dissatisfied': Icons.sentiment_dissatisfied,
    'sentiment very dissatisfied': Icons.sentiment_very_dissatisfied,
    'sentiment neutral': Icons.sentiment_neutral,
    'mood': Icons.mood,
    'mood bad': Icons.mood_bad,
    'child care': Icons.child_care,
    'child friendly': Icons.child_friendly,
    'elderly': Icons.elderly,
    'elderly woman': Icons.elderly_woman,
    'boy': Icons.boy,
    'girl': Icons.girl,
    'man': Icons.man,
    'woman': Icons.woman,
    'family restroom': Icons.family_restroom,
    'waving hand': Icons.waving_hand,
    'front hand': Icons.front_hand,
    'back hand': Icons.back_hand,
    'handshake': Icons.handshake,
    'volunteer activism': Icons.volunteer_activism,
    'thumb up': Icons.thumb_up,
    'thumb down': Icons.thumb_down,
    'sign language': Icons.sign_language,
    'accessible': Icons.accessible,
    'accessibility': Icons.accessibility,
    'accessibility new': Icons.accessibility_new,
    'pregnant woman': Icons.pregnant_woman,
    'personal injury': Icons.personal_injury,
    'diversity 1': Icons.diversity_1,
    'diversity 2': Icons.diversity_2,
    'diversity 3': Icons.diversity_3,

    // ── Communication ────────────────────────────────────────────────
    'chat': Icons.chat,
    'chat bubble': Icons.chat_bubble,
    'chat bubble outline': Icons.chat_bubble_outline,
    'message': Icons.message,
    'textsms': Icons.textsms,
    'sms': Icons.sms,
    'mms': Icons.mms,
    'forum': Icons.forum,
    'question answer': Icons.question_answer,
    'mail': Icons.mail,
    'mail outline': Icons.mail_outline,
    'email': Icons.email,
    'alternate email': Icons.alternate_email,
    'mark email read': Icons.mark_email_read,
    'mark email unread': Icons.mark_email_unread,
    'drafts': Icons.drafts,
    'send': Icons.send,
    'send and archive': Icons.send_and_archive,
    'call': Icons.call,
    'call end': Icons.call_end,
    'call made': Icons.call_made,
    'call received': Icons.call_received,
    'phone': Icons.phone,
    'phone android': Icons.phone_android,
    'phone iphone': Icons.phone_iphone,
    'phone in talk': Icons.phone_in_talk,
    'video call': Icons.video_call,
    'videocam': Icons.videocam,
    'voicemail': Icons.voicemail,
    'contact phone': Icons.contact_phone,
    'contact mail': Icons.contact_mail,
    'contacts': Icons.contacts,
    'notifications': Icons.notifications,
    'notifications active': Icons.notifications_active,
    'notifications none': Icons.notifications_none,
    'notification important': Icons.notification_important,
    'campaign': Icons.campaign,
    'announcement': Icons.announcement,
    'record voice over': Icons.record_voice_over,
    'voice over off': Icons.voice_over_off,
    'rss feed': Icons.rss_feed,
    'share': Icons.share,
    'ios share': Icons.ios_share,

    // ── Navigation & Places ──────────────────────────────────────────
    'home': Icons.home,
    'home filled': Icons.home_filled,
    'home work': Icons.home_work,
    'cottage': Icons.cottage,
    'cabin': Icons.cabin,
    'villa': Icons.villa,
    'apartment': Icons.apartment,
    'house': Icons.house,
    'location on': Icons.location_on,
    'location off': Icons.location_off,
    'location searching': Icons.location_searching,
    'my location': Icons.my_location,
    'place': Icons.place,
    'pin drop': Icons.pin_drop,
    'wrong location': Icons.wrong_location,
    'map': Icons.map,
    'explore': Icons.explore,
    'compass calibration': Icons.compass_calibration,
    'near me': Icons.near_me,
    'public': Icons.public,
    'language': Icons.language,
    'travel explore': Icons.travel_explore,
    'flight': Icons.flight,
    'flight takeoff': Icons.flight_takeoff,
    'flight land': Icons.flight_land,
    'local airport': Icons.local_airport,
    'connecting airports': Icons.connecting_airports,
    'directions car': Icons.directions_car,
    'directions bus': Icons.directions_bus,
    'train': Icons.train,
    'tram': Icons.tram,
    'subway': Icons.subway,
    'two wheeler': Icons.two_wheeler,
    'electric car': Icons.electric_car,
    'electric scooter': Icons.electric_scooter,
    'sailing': Icons.sailing,
    'kayaking': Icons.kayaking,
    'local shipping': Icons.local_shipping,
    'rocket launch': Icons.rocket_launch,
    'rocket': Icons.rocket,
    'navigation': Icons.navigation,
    'north': Icons.north,
    'south': Icons.south,
    'east': Icons.east,
    'west': Icons.west,

    // ── Work & Business ──────────────────────────────────────────────
    'work': Icons.work,
    'work outline': Icons.work_outline,
    'work history': Icons.work_history,
    'business center': Icons.business_center,
    'business': Icons.business,
    'corporate fare': Icons.corporate_fare,
    'domain': Icons.domain,
    'meeting room': Icons.meeting_room,
    'door front': Icons.door_front_door,
    'badge': Icons.badge,
    'assignment': Icons.assignment,
    'assignment ind': Icons.assignment_ind,
    'assignment turned in': Icons.assignment_turned_in,
    'assignment late': Icons.assignment_late,
    'assignment return': Icons.assignment_return,
    'description': Icons.description,
    'article': Icons.article,
    'newspaper': Icons.newspaper,
    'feed': Icons.feed,
    'note': Icons.note,
    'note add': Icons.note_add,
    'sticky note': Icons.sticky_note_2,
    'post add': Icons.post_add,
    'folder': Icons.folder,
    'folder open': Icons.folder_open,
    'folder shared': Icons.folder_shared,
    'folder special': Icons.folder_special,
    'create new folder': Icons.create_new_folder,
    'topic': Icons.topic,
    'inventory': Icons.inventory,
    'inventory 2': Icons.inventory_2,
    'archive': Icons.archive,
    'unarchive': Icons.unarchive,
    'attach file': Icons.attach_file,
    'attachment': Icons.attachment,
    'task': Icons.task,
    'task alt': Icons.task_alt,
    'checklist': Icons.checklist,
    'rule': Icons.rule,
    'pending actions': Icons.pending_actions,
    'schedule': Icons.schedule,
    'event': Icons.event,
    'event available': Icons.event_available,
    'calendar today': Icons.calendar_today,
    'calendar month': Icons.calendar_month,
    'date range': Icons.date_range,
    'today': Icons.today,
    'timeline': Icons.timeline,
    'receipt': Icons.receipt,
    'receipt long': Icons.receipt_long,

    // ── Education & Science ──────────────────────────────────────────
    'school': Icons.school,
    'menu book': Icons.menu_book,
    'auto stories': Icons.auto_stories,
    'library books': Icons.library_books,
    'local library': Icons.local_library,
    'import contacts': Icons.import_contacts,
    'class': Icons.class_,
    'biotech': Icons.biotech,
    'science': Icons.science,
    'psychology': Icons.psychology,
    'psychology alt': Icons.psychology_alt,
    'calculate': Icons.calculate,
    'functions': Icons.functions,
    'architecture': Icons.architecture,
    'engineering': Icons.engineering,
    'history edu': Icons.history_edu,
    'history': Icons.history,
    'translate': Icons.translate,
    'spellcheck': Icons.spellcheck,
    'model training': Icons.model_training,
    'hub': Icons.hub,
    'scatter plot': Icons.scatter_plot,
    'insights': Icons.insights,
    'analytics': Icons.analytics,
    'data usage': Icons.data_usage,

    // ── Entertainment & Media ────────────────────────────────────────
    'music note': Icons.music_note,
    'music off': Icons.music_off,
    'queue music': Icons.queue_music,
    'library music': Icons.library_music,
    'audiotrack': Icons.audiotrack,
    'album': Icons.album,
    'headphones': Icons.headphones,
    'headset': Icons.headset,
    'earbuds': Icons.earbuds,
    'speaker': Icons.speaker,
    'radio': Icons.radio,
    'mic': Icons.mic,
    'mic off': Icons.mic_off,
    'piano': Icons.piano,
    'movie': Icons.movie,
    'movie creation': Icons.movie_creation,
    'theaters': Icons.theaters,
    'live tv': Icons.live_tv,
    'tv': Icons.tv,
    'monitor': Icons.monitor,
    'connected tv': Icons.connected_tv,
    'ondemand video': Icons.ondemand_video,
    'subscriptions': Icons.subscriptions,
    'video library': Icons.video_library,
    'camera': Icons.camera,
    'camera alt': Icons.camera_alt,
    'camera front': Icons.camera_front,
    'camera rear': Icons.camera_rear,
    'photo camera': Icons.photo_camera,
    'photo camera front': Icons.photo_camera_front,
    'photo camera back': Icons.photo_camera_back,
    'photo': Icons.photo,
    'photo album': Icons.photo_album,
    'photo library': Icons.photo_library,
    'image': Icons.image,
    'panorama': Icons.panorama,
    'collections': Icons.collections,
    'palette': Icons.palette,
    'brush': Icons.brush,
    'format paint': Icons.format_paint,
    'color lens': Icons.color_lens,
    'gradient': Icons.gradient,
    'texture': Icons.texture,
    'videogame asset': Icons.videogame_asset,
    'sports esports': Icons.sports_esports,
    'casino': Icons.casino,
    'extension': Icons.extension,
    'smart toy': Icons.smart_toy,
    'toys': Icons.toys,
    'animation': Icons.animation,
    'auto fix high': Icons.auto_fix_high,
    'draw': Icons.draw,
    'create': Icons.create,
    'edit': Icons.edit,
    'design services': Icons.design_services,
    'art track': Icons.art_track,

    // ── Food & Drink ─────────────────────────────────────────────────
    'restaurant': Icons.restaurant,
    'restaurant menu': Icons.restaurant_menu,
    'local dining': Icons.local_dining,
    'dining': Icons.dining,
    'brunch dining': Icons.brunch_dining,
    'lunch dining': Icons.lunch_dining,
    'dinner dining': Icons.dinner_dining,
    'bakery dining': Icons.bakery_dining,
    'fastfood': Icons.fastfood,
    'local pizza': Icons.local_pizza,
    'cake': Icons.cake,
    'icecream': Icons.icecream,
    'cookie': Icons.cookie,
    'local cafe': Icons.local_cafe,
    'coffee': Icons.coffee,
    'coffee maker': Icons.coffee_maker,
    'local bar': Icons.local_bar,
    'wine bar': Icons.wine_bar,
    'liquor': Icons.liquor,
    'nightlife': Icons.nightlife,
    'sports bar': Icons.sports_bar,
    'tapas': Icons.tapas,
    'ramen dining': Icons.ramen_dining,
    'kebab dining': Icons.kebab_dining,
    'egg': Icons.egg,
    'egg alt': Icons.egg_alt,
    'set meal': Icons.set_meal,
    'rice bowl': Icons.rice_bowl,
    'kitchen': Icons.kitchen,
    'microwave': Icons.microwave,
    'outdoor grill': Icons.outdoor_grill,
    'takeout dining': Icons.takeout_dining,
    'delivery dining': Icons.delivery_dining,

    // ── Nature & Animals ─────────────────────────────────────────────
    'pets': Icons.pets,
    'cruelty free': Icons.cruelty_free,
    'park': Icons.park,
    'forest': Icons.forest,
    'nature': Icons.nature,
    'nature people': Icons.nature_people,
    'grass': Icons.grass,
    'eco': Icons.eco,
    'compost': Icons.compost,
    'recycling': Icons.recycling,
    'spa': Icons.spa,
    'local florist': Icons.local_florist,
    'yard': Icons.yard,
    'water': Icons.water,
    'water drop': Icons.water_drop,
    'waves': Icons.waves,
    'pool': Icons.pool,
    'terrain': Icons.terrain,
    'landscape': Icons.landscape,
    'volcano': Icons.volcano,
    'tsunami': Icons.tsunami,
    'flood': Icons.flood,
    'beach access': Icons.beach_access,
    'sunny': Icons.wb_sunny,
    'sunny snowy': Icons.wb_twilight,
    'cloudy': Icons.wb_cloudy,
    'cloud': Icons.cloud,
    'cloud queue': Icons.cloud_queue,
    'thunderstorm': Icons.thunderstorm,
    'ac unit': Icons.ac_unit,
    'snowing': Icons.snowing,
    'dew point': Icons.dew_point,
    'air': Icons.air,
    'wind power': Icons.wind_power,
    'tornado': Icons.tornado,
    'cyclone': Icons.cyclone,
    'solar power': Icons.solar_power,
    'energy savings leaf': Icons.energy_savings_leaf,
    'pest control': Icons.pest_control,

    // ── Sports & Fitness ─────────────────────────────────────────────
    'fitness center': Icons.fitness_center,
    'sports soccer': Icons.sports_soccer,
    'sports basketball': Icons.sports_basketball,
    'sports baseball': Icons.sports_baseball,
    'sports tennis': Icons.sports_tennis,
    'sports golf': Icons.sports_golf,
    'sports volleyball': Icons.sports_volleyball,
    'sports handball': Icons.sports_handball,
    'sports hockey': Icons.sports_hockey,
    'sports rugby': Icons.sports_rugby,
    'sports football': Icons.sports_football,
    'sports cricket': Icons.sports_cricket,
    'sports kabaddi': Icons.sports_kabaddi,
    'sports martial arts': Icons.sports_martial_arts,
    'sports gymnastics': Icons.sports_gymnastics,
    'sports motorsports': Icons.sports_motorsports,
    'sports score': Icons.sports_score,
    'surfing': Icons.surfing,
    'skateboarding': Icons.skateboarding,
    'snowboarding': Icons.snowboarding,
    'snowshoeing': Icons.snowshoeing,
    'ice skating': Icons.ice_skating,
    'sledding': Icons.sledding,
    'paragliding': Icons.paragliding,
    'kitesurfing': Icons.kitesurfing,
    'scuba diving': Icons.scuba_diving,
    'hiking': Icons.hiking,
    'directions bike': Icons.directions_bike,
    'directions run': Icons.directions_run,
    'directions walk': Icons.directions_walk,
    'nordic walking': Icons.nordic_walking,
    'self improvement': Icons.self_improvement,
    'downhill skiing': Icons.downhill_skiing,

    // ── Health & Medical ─────────────────────────────────────────────
    'favorite': Icons.favorite,
    'favorite border': Icons.favorite_border,
    'heart broken': Icons.heart_broken,
    'health and safety': Icons.health_and_safety,
    'medical services': Icons.medical_services,
    'medical information': Icons.medical_information,
    'local hospital': Icons.local_hospital,
    'local pharmacy': Icons.local_pharmacy,
    'medication': Icons.medication,
    'medication liquid': Icons.medication_liquid,
    'vaccines': Icons.vaccines,
    'healing': Icons.healing,
    'monitor heart': Icons.monitor_heart,
    'monitor weight': Icons.monitor_weight,
    'bloodtype': Icons.bloodtype,
    'masks': Icons.masks,
    'sanitizer': Icons.sanitizer,
    'sick': Icons.sick,
    'coronavirus': Icons.coronavirus,

    // ── Technology & Devices ─────────────────────────────────────────
    'computer': Icons.computer,
    'desktop windows': Icons.desktop_windows,
    'desktop mac': Icons.desktop_mac,
    'laptop': Icons.laptop,
    'laptop mac': Icons.laptop_mac,
    'laptop chromebook': Icons.laptop_chromebook,
    'smartphone': Icons.smartphone,
    'tablet': Icons.tablet,
    'tablet mac': Icons.tablet_mac,
    'watch': Icons.watch,
    'watch later': Icons.watch_later,
    'keyboard': Icons.keyboard,
    'mouse': Icons.mouse,
    'headset mic': Icons.headset_mic,
    'memory': Icons.memory,
    'sd card': Icons.sd_card,
    'sim card': Icons.sim_card,
    'developer board': Icons.developer_board,
    'developer mode': Icons.developer_mode,
    'code': Icons.code,
    'code off': Icons.code_off,
    'terminal': Icons.terminal,
    'data object': Icons.data_object,
    'data array': Icons.data_array,
    'bug report': Icons.bug_report,
    'api': Icons.api,
    'webhook': Icons.webhook,
    'dns': Icons.dns,
    'storage': Icons.storage,
    'database': Icons.storage,
    'cloud upload': Icons.cloud_upload,
    'cloud download': Icons.cloud_download,
    'cloud done': Icons.cloud_done,
    'cloud sync': Icons.cloud_sync,
    'cloud off': Icons.cloud_off,
    'wifi': Icons.wifi,
    'wifi off': Icons.wifi_off,
    'signal wifi 4 bar': Icons.signal_wifi_4_bar,
    'signal cellular alt': Icons.signal_cellular_alt,
    'bluetooth': Icons.bluetooth,
    'bluetooth connected': Icons.bluetooth_connected,
    'nfc': Icons.nfc,
    'usb': Icons.usb,
    'router': Icons.router,
    'devices': Icons.devices,
    'cast': Icons.cast,
    'screen share': Icons.screen_share,
    'print': Icons.print,
    'scanner': Icons.scanner,
    'qr code': Icons.qr_code,
    'qr code scanner': Icons.qr_code_scanner,
    'battery full': Icons.battery_full,
    'battery charging full': Icons.battery_charging_full,
    'power': Icons.power,
    'electrical services': Icons.electrical_services,

    // ── Shapes & Symbols ─────────────────────────────────────────────
    'star': Icons.star,
    'star border': Icons.star_border,
    'star half': Icons.star_half,
    'star rate': Icons.star_rate,
    'stars': Icons.stars,
    'circle': Icons.circle,
    'square': Icons.square,
    'rectangle': Icons.rectangle,
    'hexagon': Icons.hexagon,
    'pentagon': Icons.pentagon,
    'diamond': Icons.diamond,
    'change history': Icons.change_history,
    'category': Icons.category,
    'interests': Icons.interests,
    'auto awesome': Icons.auto_awesome,
    'auto awesome mosaic': Icons.auto_awesome_mosaic,
    'flash on': Icons.flash_on,
    'flash off': Icons.flash_off,
    'bolt': Icons.bolt,
    'electric bolt': Icons.electric_bolt,
    'whatshot': Icons.whatshot,
    'local fire department': Icons.local_fire_department,
    'flare': Icons.flare,
    'lens flare': Icons.lens_blur,
    'light mode': Icons.light_mode,
    'dark mode': Icons.dark_mode,
    'nightlight': Icons.nightlight,
    'brightness high': Icons.brightness_high,
    'brightness low': Icons.brightness_low,
    'contrast': Icons.contrast,
    'blur on': Icons.blur_on,
    'grain': Icons.grain,
    'all inclusive': Icons.all_inclusive,
    'gesture': Icons.gesture,
    'fingerprint': Icons.fingerprint,

    // ── Objects & Tools ──────────────────────────────────────────────
    'construction': Icons.construction,
    'build': Icons.build,
    'build circle': Icons.build_circle,
    'handyman': Icons.handyman,
    'plumbing': Icons.plumbing,
    'carpenter': Icons.carpenter,
    'hardware': Icons.hardware,
    'settings': Icons.settings,
    'settings suggest': Icons.settings_suggest,
    'tune': Icons.tune,
    'key': Icons.key,
    'key off': Icons.key_off,
    'lock': Icons.lock,
    'lock open': Icons.lock_open,
    'lock clock': Icons.lock_clock,
    'vpn key': Icons.vpn_key,
    'password': Icons.password,
    'pin': Icons.pin,
    'shield': Icons.shield,
    'shield moon': Icons.shield_moon,
    'security': Icons.security,
    'admin panel settings': Icons.admin_panel_settings,
    'verified': Icons.verified,
    'verified user': Icons.verified_user,
    'gavel': Icons.gavel,
    'balance': Icons.balance,
    'policy': Icons.policy,
    'savings': Icons.savings,
    'account balance': Icons.account_balance,
    'account balance wallet': Icons.account_balance_wallet,
    'wallet': Icons.wallet,
    'payments': Icons.payments,
    'credit card': Icons.credit_card,
    'currency exchange': Icons.currency_exchange,
    'price change': Icons.price_change,
    'shopping cart': Icons.shopping_cart,
    'shopping bag': Icons.shopping_bag,
    'shopping basket': Icons.shopping_basket,
    'add shopping cart': Icons.add_shopping_cart,
    'storefront': Icons.storefront,
    'store': Icons.store,
    'local mall': Icons.local_mall,
    'redeem': Icons.redeem,
    'card giftcard': Icons.card_giftcard,
    'card membership': Icons.card_membership,
    'loyalty': Icons.loyalty,
    'sell': Icons.sell,
    'local offer': Icons.local_offer,
    'discount': Icons.discount,
    'percent': Icons.percent,

    // ── Awards & Celebration ─────────────────────────────────────────
    'emoji events': Icons.emoji_events,
    'military tech': Icons.military_tech,
    'workspace premium': Icons.workspace_premium,
    'celebration': Icons.celebration,
    'party mode': Icons.party_mode,

    // ── Arrows & Actions ─────────────────────────────────────────────
    'flag': Icons.flag,
    'flag circle': Icons.flag_circle,
    'outlined flag': Icons.outlined_flag,
    'tour': Icons.tour,
    'bookmark': Icons.bookmark,
    'bookmark border': Icons.bookmark_border,
    'bookmark add': Icons.bookmark_add,
    'bookmarks': Icons.bookmarks,
    'push pin': Icons.push_pin,
    'label': Icons.label,
    'label important': Icons.label_important,
    'lightbulb': Icons.lightbulb,
    'lightbulb circle': Icons.lightbulb_circle,
    'tips and updates': Icons.tips_and_updates,
    'info': Icons.info,
    'info outline': Icons.info_outline,
    'help': Icons.help,
    'help outline': Icons.help_outline,
    'question mark': Icons.question_mark,
    'warning': Icons.warning,
    'warning amber': Icons.warning_amber,
    'error': Icons.error,
    'error outline': Icons.error_outline,
    'priority high': Icons.priority_high,
    'new releases': Icons.new_releases,
    'report': Icons.report,
    'report problem': Icons.report_problem,

    // ── Religion & Culture ───────────────────────────────────────────
    'church': Icons.church,
    'mosque': Icons.mosque,
    'temple hindu': Icons.temple_hindu,
    'temple buddhist': Icons.temple_buddhist,
    'synagogue': Icons.synagogue,
    'fort': Icons.fort,
    'castle': Icons.castle,
    'stadium': Icons.stadium,
    'museum': Icons.museum,

    // ── Home & Living ────────────────────────────────────────────────
    'bed': Icons.bed,
    'bedroom parent': Icons.bedroom_parent,
    'bedroom child': Icons.bedroom_child,
    'bathroom': Icons.bathroom,
    'bathtub': Icons.bathtub,
    'shower': Icons.shower,
    'living': Icons.living,
    'chair': Icons.chair,
    'chair alt': Icons.chair_alt,
    'table bar': Icons.table_bar,
    'table restaurant': Icons.table_restaurant,
    'door back': Icons.door_back_door,
    'door sliding': Icons.door_sliding,
    'window': Icons.window,
    'roofing': Icons.roofing,
    'foundation': Icons.foundation,
    'fence': Icons.fence,
    'deck': Icons.deck,
    'balcony': Icons.balcony,
    'garage': Icons.garage,
    'light': Icons.light,
    'nightlight round': Icons.nightlight_round,
    'curtains': Icons.curtains,
    'blinds': Icons.blinds,

    // ── Clothing & Fashion ───────────────────────────────────────────
    'checkroom': Icons.checkroom,
    'dry cleaning': Icons.dry_cleaning,
    'iron': Icons.iron,
    'backpack': Icons.backpack,
    'luggage': Icons.luggage,
    'goggles': Icons.sports_motorsports,

    // ── Signs & Indicators ───────────────────────────────────────────
    'check circle': Icons.check_circle,
    'check circle outline': Icons.check_circle_outline,
    'check': Icons.check,
    'done': Icons.done,
    'done all': Icons.done_all,
    'close': Icons.close,
    'cancel': Icons.cancel,
    'block': Icons.block,
    'do not disturb': Icons.do_not_disturb,
    'not interested': Icons.not_interested,
    'remove circle': Icons.remove_circle,
    'add circle': Icons.add_circle,
    'add circle outline': Icons.add_circle_outline,
    'add': Icons.add,
    'remove': Icons.remove,

    // ── Transportation ───────────────────────────────────────────────
    'airport shuttle': Icons.airport_shuttle,
    'local taxi': Icons.local_taxi,
    'directions boat': Icons.directions_boat,
    'pedal bike': Icons.pedal_bike,
    'electric bike': Icons.electric_bike,
    'electric moped': Icons.electric_moped,
    'motorcycle': Icons.motorcycle,
    'directions railway': Icons.directions_railway,
    'commute': Icons.commute,
    'transfer within a station': Icons.transfer_within_a_station,
    'bus alert': Icons.bus_alert,
    'car rental': Icons.car_rental,
    'car repair': Icons.car_repair,
    'local gas station': Icons.local_gas_station,
    'ev station': Icons.ev_station,
    'local parking': Icons.local_parking,
    'traffic': Icons.traffic,
    'emergency': Icons.emergency,

    // ── Miscellaneous ────────────────────────────────────────────────
    'anchor': Icons.anchor,
    'catching pokemon': Icons.catching_pokemon,
    'hive': Icons.hive,
    'token': Icons.token,
    'tag': Icons.tag,
    'apps': Icons.apps,
    'widgets': Icons.widgets,
    'dashboard': Icons.dashboard,
    'grid view': Icons.grid_view,
    'view module': Icons.view_module,
    'space dashboard': Icons.space_dashboard,
    'more horiz': Icons.more_horiz,
    'more vert': Icons.more_vert,
    'menu': Icons.menu,
    'toc': Icons.toc,
    'list': Icons.list,
    'view list': Icons.view_list,
    'sort': Icons.sort,
    'filter list': Icons.filter_list,
    'search': Icons.search,
    'zoom in': Icons.zoom_in,
    'zoom out': Icons.zoom_out,
    'refresh': Icons.refresh,
    'sync': Icons.sync,
    'loop': Icons.loop,
    'replay': Icons.replay,
    'swap horiz': Icons.swap_horiz,
    'swap vert': Icons.swap_vert,
    'compare arrows': Icons.compare_arrows,
    'open in new': Icons.open_in_new,
    'launch': Icons.launch,
    'link': Icons.link,
    'link off': Icons.link_off,
    'copy': Icons.copy,
    'content copy': Icons.content_copy,
    'content paste': Icons.content_paste,
    'content cut': Icons.content_cut,
    'save': Icons.save,
    'save alt': Icons.save_alt,
    'download': Icons.download,
    'upload': Icons.upload,
    'file download': Icons.file_download,
    'file upload': Icons.file_upload,
    'delete': Icons.delete,
    'delete forever': Icons.delete_forever,
    'restore from trash': Icons.restore_from_trash,
    'undo': Icons.undo,
    'redo': Icons.redo,
    'visibility': Icons.visibility,
    'visibility off': Icons.visibility_off,
    'remove red eye': Icons.remove_red_eye,
    'preview': Icons.preview,
    'speed': Icons.speed,
    'timelapse': Icons.timelapse,
    'timer': Icons.timer,
    'hourglass empty': Icons.hourglass_empty,
    'hourglass full': Icons.hourglass_full,
    'alarm': Icons.alarm,
    'alarm on': Icons.alarm_on,
    'alarm add': Icons.alarm_add,
    'snooze': Icons.snooze,
    'bedtime': Icons.bedtime,
    'thermostat': Icons.thermostat,
    'device thermostat': Icons.device_thermostat,
    'local laundry service': Icons.local_laundry_service,
    'local car wash': Icons.local_car_wash,
    'local atm': Icons.local_atm,
    'local activity': Icons.local_activity,
    'local play': Icons.local_play,
    'local movies': Icons.local_movies,
    'local grocery store': Icons.local_grocery_store,
    'local convenience store': Icons.local_convenience_store,
    'local printshop': Icons.local_printshop,
    'local post office': Icons.local_post_office,
    'local police': Icons.local_police,
    'pest control rodent': Icons.pest_control_rodent,
    'scale': Icons.scale,
    'straighten': Icons.straighten,
    'square foot': Icons.square_foot,
    'aspect ratio': Icons.aspect_ratio,
    'crop': Icons.crop,
    'transform': Icons.transform,
    'rotate left': Icons.rotate_left,
    'rotate right': Icons.rotate_right,
    'flip': Icons.flip,
    'photo filter': Icons.photo_filter,
    'filter': Icons.filter,
    'filter vintage': Icons.filter_vintage,
    'filter drama': Icons.filter_drama,
    'filter hdr': Icons.filter_hdr,
    'vignette': Icons.vignette,
    'style': Icons.style,
    'format quote': Icons.format_quote,
    'format shapes': Icons.format_shapes,
    'text fields': Icons.text_fields,
    'title': Icons.title,
    'short text': Icons.short_text,
    'notes': Icons.notes,
    'border color': Icons.border_color,
    'highlight': Icons.highlight,
    'colorize': Icons.colorize,
    'invert colors': Icons.invert_colors,
    'opacity': Icons.opacity,
  };

  /// Reverse tag index: tag keyword → list of icon names that match.
  static const Map<String, List<String>> _tagIndex = {
    // People synonyms
    'user': [
      'person',
      'person outline',
      'person add',
      'person remove',
      'person search',
      'person pin',
      'person pin circle',
      'face',
      'badge',
      'accessibility',
      'accessibility new'
    ],
    'profile': [
      'person',
      'person outline',
      'face',
      'face 2',
      'face 3',
      'face 4',
      'face 5',
      'face 6',
      'badge',
      'account balance'
    ],
    'avatar': [
      'person',
      'person outline',
      'face',
      'face 2',
      'face 3',
      'emoji emotions',
      'emoji people'
    ],
    'human': [
      'person',
      'person outline',
      'people',
      'group',
      'groups',
      'boy',
      'girl',
      'man',
      'woman',
      'elderly',
      'child care',
      'accessibility'
    ],
    'member': [
      'person',
      'person add',
      'group',
      'group add',
      'groups',
      'badge',
      'card membership'
    ],
    'friend': [
      'people',
      'group',
      'groups',
      'diversity 1',
      'diversity 2',
      'diversity 3',
      'handshake',
      'waving hand'
    ],
    'team': [
      'people',
      'group',
      'groups',
      'diversity 1',
      'diversity 2',
      'diversity 3',
      'corporate fare'
    ],
    'community': [
      'groups',
      'people',
      'forum',
      'diversity 1',
      'diversity 2',
      'diversity 3',
      'public'
    ],
    'happy': [
      'sentiment satisfied',
      'sentiment very satisfied',
      'mood',
      'emoji emotions',
      'celebration',
      'party mode'
    ],
    'sad': [
      'sentiment dissatisfied',
      'sentiment very dissatisfied',
      'mood bad',
      'sick'
    ],
    'smile': [
      'sentiment satisfied',
      'sentiment very satisfied',
      'mood',
      'emoji emotions',
      'face'
    ],
    'baby': ['child care', 'child friendly', 'boy', 'girl', 'pregnant woman'],
    'family': [
      'family restroom',
      'child care',
      'child friendly',
      'boy',
      'girl',
      'man',
      'woman',
      'elderly',
      'pregnant woman'
    ],
    'old': ['elderly', 'elderly woman', 'history'],
    'wave': ['waving hand', 'waves', 'front hand'],
    'like': ['thumb up', 'favorite', 'star', 'sentiment satisfied'],
    'dislike': [
      'thumb down',
      'sentiment dissatisfied',
      'mood bad',
      'block',
      'not interested'
    ],
    'love': [
      'favorite',
      'favorite border',
      'heart broken',
      'volunteer activism'
    ],
    'heart': ['favorite', 'favorite border', 'heart broken', 'monitor heart'],
    'hand': [
      'waving hand',
      'front hand',
      'back hand',
      'handshake',
      'sign language',
      'volunteer activism',
      'thumb up',
      'thumb down'
    ],

    // Communication synonyms
    'talk': [
      'chat',
      'chat bubble',
      'message',
      'forum',
      'phone in talk',
      'record voice over',
      'question answer'
    ],
    'text': [
      'textsms',
      'sms',
      'message',
      'chat',
      'chat bubble',
      'text fields',
      'short text'
    ],
    'conversation': [
      'chat',
      'forum',
      'question answer',
      'message',
      'chat bubble'
    ],
    'discuss': ['forum', 'question answer', 'chat', 'groups', 'meeting room'],
    'letter': ['mail', 'mail outline', 'email', 'drafts', 'send'],
    'inbox': [
      'mail',
      'email',
      'drafts',
      'mark email read',
      'mark email unread'
    ],
    'ring': ['call', 'phone', 'notifications', 'notifications active', 'alarm'],
    'dial': ['call', 'phone', 'phone in talk', 'dialpad'],
    'alert': [
      'notifications',
      'notifications active',
      'notification important',
      'warning',
      'priority high',
      'bus alert',
      'error'
    ],
    'bell': [
      'notifications',
      'notifications active',
      'notifications none',
      'notification important'
    ],
    'broadcast': [
      'campaign',
      'announcement',
      'rss feed',
      'record voice over',
      'share'
    ],
    'video': [
      'video call',
      'videocam',
      'video library',
      'movie',
      'ondemand video',
      'live tv'
    ],

    // Navigation & Places synonyms
    'house': [
      'home',
      'home filled',
      'house',
      'cottage',
      'cabin',
      'villa',
      'apartment',
      'home work'
    ],
    'building': [
      'apartment',
      'business',
      'corporate fare',
      'domain',
      'castle',
      'fort',
      'stadium',
      'museum'
    ],
    'address': ['location on', 'place', 'pin drop', 'my location', 'home'],
    'gps': [
      'location on',
      'my location',
      'location searching',
      'near me',
      'navigation',
      'explore'
    ],
    'direction': [
      'navigation',
      'north',
      'south',
      'east',
      'west',
      'near me',
      'explore',
      'compass calibration'
    ],
    'world': [
      'public',
      'language',
      'travel explore',
      'flight',
      'map',
      'explore'
    ],
    'globe': ['public', 'language', 'travel explore'],
    'plane': [
      'flight',
      'flight takeoff',
      'flight land',
      'local airport',
      'connecting airports'
    ],
    'airplane': ['flight', 'flight takeoff', 'flight land', 'local airport'],
    'travel': [
      'flight',
      'travel explore',
      'luggage',
      'local airport',
      'hotel',
      'map',
      'explore'
    ],
    'car': [
      'directions car',
      'electric car',
      'car rental',
      'car repair',
      'local gas station',
      'two wheeler'
    ],
    'bus': ['directions bus', 'airport shuttle', 'bus alert', 'commute'],
    'ship': [
      'sailing',
      'local shipping',
      'directions boat',
      'kayaking',
      'anchor'
    ],
    'boat': ['sailing', 'directions boat', 'kayaking', 'anchor'],
    'space': ['rocket launch', 'rocket', 'star', 'stars', 'auto awesome'],

    // Work & Business synonyms
    'job': [
      'work',
      'work outline',
      'work history',
      'business center',
      'badge',
      'engineering'
    ],
    'office': [
      'work',
      'business center',
      'business',
      'corporate fare',
      'domain',
      'meeting room',
      'badge'
    ],
    'company': ['business', 'corporate fare', 'domain', 'storefront', 'store'],
    'document': [
      'description',
      'article',
      'note',
      'sticky note',
      'assignment',
      'receipt',
      'newspaper'
    ],
    'paper': [
      'description',
      'article',
      'note',
      'newspaper',
      'receipt',
      'receipt long'
    ],
    'file': [
      'folder',
      'folder open',
      'attach file',
      'attachment',
      'description',
      'topic'
    ],
    'todo': [
      'task',
      'task alt',
      'checklist',
      'rule',
      'assignment',
      'pending actions',
      'done',
      'done all'
    ],
    'meeting': [
      'meeting room',
      'groups',
      'event',
      'calendar today',
      'schedule',
      'video call'
    ],
    'appointment': [
      'event',
      'event available',
      'calendar today',
      'calendar month',
      'date range',
      'schedule'
    ],
    'date': [
      'calendar today',
      'calendar month',
      'date range',
      'today',
      'event',
      'schedule'
    ],
    'time': [
      'schedule',
      'timer',
      'hourglass empty',
      'hourglass full',
      'watch',
      'watch later',
      'alarm',
      'timelapse'
    ],
    'clock': [
      'schedule',
      'timer',
      'watch',
      'watch later',
      'alarm',
      'alarm on',
      'alarm add',
      'hourglass empty'
    ],
    'news': [
      'newspaper',
      'feed',
      'article',
      'campaign',
      'announcement',
      'new releases'
    ],

    // Education synonyms
    'study': [
      'school',
      'menu book',
      'auto stories',
      'library books',
      'local library',
      'class',
      'history edu'
    ],
    'learn': [
      'school',
      'menu book',
      'auto stories',
      'library books',
      'model training',
      'psychology'
    ],
    'book': [
      'menu book',
      'auto stories',
      'library books',
      'local library',
      'import contacts',
      'class'
    ],
    'read': [
      'menu book',
      'auto stories',
      'library books',
      'chrome reader mode',
      'article'
    ],
    'university': ['school', 'history edu', 'class', 'library books'],
    'college': ['school', 'history edu', 'class'],
    'math': ['calculate', 'functions', 'analytics', 'insights', 'scatter plot'],
    'lab': ['biotech', 'science', 'psychology'],
    'experiment': ['biotech', 'science'],
    'brain': ['psychology', 'psychology alt', 'model training', 'smart toy'],
    'mind': ['psychology', 'psychology alt', 'self improvement'],
    'chart': [
      'analytics',
      'insights',
      'scatter plot',
      'data usage',
      'timeline'
    ],
    'graph': [
      'analytics',
      'insights',
      'scatter plot',
      'timeline',
      'data usage'
    ],
    'data': [
      'analytics',
      'data usage',
      'data object',
      'data array',
      'scatter plot',
      'insights',
      'storage'
    ],

    // Entertainment synonyms
    'song': [
      'music note',
      'audiotrack',
      'queue music',
      'library music',
      'album'
    ],
    'audio': [
      'music note',
      'audiotrack',
      'headphones',
      'headset',
      'earbuds',
      'speaker',
      'radio',
      'mic',
      'volume up'
    ],
    'listen': ['headphones', 'headset', 'earbuds', 'radio', 'music note'],
    'sing': ['mic', 'music note', 'audiotrack', 'karaoke'],
    'instrument': ['piano', 'music note', 'audiotrack'],
    'film': [
      'movie',
      'movie creation',
      'theaters',
      'live tv',
      'videocam',
      'ondemand video'
    ],
    'cinema': ['movie', 'theaters', 'live tv'],
    'show': ['tv', 'live tv', 'connected tv', 'subscriptions', 'theaters'],
    'picture': [
      'photo',
      'photo camera',
      'image',
      'photo album',
      'photo library',
      'panorama',
      'camera'
    ],
    'snapshot': ['camera', 'camera alt', 'photo camera', 'photo'],
    'selfie': ['camera front', 'photo camera front', 'face'],
    'art': [
      'palette',
      'brush',
      'color lens',
      'draw',
      'design services',
      'art track',
      'format paint'
    ],
    'paint': ['palette', 'brush', 'format paint', 'color lens', 'colorize'],
    'game': [
      'videogame asset',
      'sports esports',
      'casino',
      'extension',
      'smart toy',
      'toys'
    ],
    'play': [
      'videogame asset',
      'sports esports',
      'local play',
      'smart toy',
      'toys'
    ],
    'magic': [
      'auto fix high',
      'auto awesome',
      'auto awesome mosaic',
      'smart toy'
    ],
    'wand': ['auto fix high', 'auto awesome'],

    // Food & Drink synonyms
    'eat': [
      'restaurant',
      'local dining',
      'dining',
      'fastfood',
      'lunch dining',
      'dinner dining'
    ],
    'food': [
      'restaurant',
      'local dining',
      'fastfood',
      'local pizza',
      'cake',
      'set meal',
      'bakery dining',
      'ramen dining',
      'egg',
      'rice bowl',
      'kebab dining',
      'tapas',
      'cookie',
      'icecream'
    ],
    'meal': [
      'restaurant',
      'set meal',
      'lunch dining',
      'dinner dining',
      'brunch dining',
      'rice bowl'
    ],
    'drink': [
      'local cafe',
      'coffee',
      'local bar',
      'wine bar',
      'liquor',
      'nightlife',
      'sports bar'
    ],
    'tea': ['local cafe', 'coffee', 'emoji food beverage'],
    'beer': ['sports bar', 'local bar', 'nightlife'],
    'wine': ['wine bar', 'liquor', 'local bar'],
    'cook': ['kitchen', 'microwave', 'outdoor grill', 'restaurant menu'],
    'pizza': ['local pizza', 'fastfood'],
    'dessert': ['cake', 'icecream', 'cookie', 'bakery dining'],
    'sweet': ['cake', 'icecream', 'cookie', 'bakery dining'],
    'breakfast': [
      'egg',
      'egg alt',
      'brunch dining',
      'coffee',
      'local cafe',
      'bakery dining'
    ],
    'noodle': ['ramen dining', 'set meal', 'rice bowl'],

    // Nature synonyms
    'animal': ['pets', 'cruelty free', 'pest control', 'pest control rodent'],
    'dog': ['pets'],
    'cat': ['pets'],
    'paw': ['pets'],
    'bunny': ['cruelty free'],
    'rabbit': ['cruelty free'],
    'tree': [
      'park',
      'forest',
      'nature',
      'nature people',
      'eco',
      'energy savings leaf'
    ],
    'plant': [
      'local florist',
      'yard',
      'grass',
      'eco',
      'compost',
      'spa',
      'energy savings leaf'
    ],
    'flower': ['local florist', 'yard', 'spa', 'filter vintage'],
    'garden': ['yard', 'local florist', 'grass', 'park', 'fence', 'deck'],
    'green': [
      'eco',
      'compost',
      'recycling',
      'energy savings leaf',
      'park',
      'forest',
      'nature'
    ],
    'ocean': [
      'water',
      'waves',
      'pool',
      'beach access',
      'sailing',
      'anchor',
      'surfing',
      'scuba diving'
    ],
    'sea': ['water', 'waves', 'beach access', 'sailing', 'anchor', 'surfing'],
    'river': ['water', 'water drop', 'waves', 'kayaking'],
    'rain': ['water drop', 'thunderstorm', 'cloudy', 'cloud'],
    'snow': [
      'ac unit',
      'snowing',
      'snowboarding',
      'snowshoeing',
      'ice skating',
      'sledding'
    ],
    'ice': ['ac unit', 'snowing', 'ice skating', 'icecream'],
    'mountain': ['terrain', 'landscape', 'hiking', 'filter hdr', 'volcano'],
    'sun': [
      'sunny',
      'light mode',
      'brightness high',
      'solar power',
      'beach access',
      'flare'
    ],
    'moon': [
      'dark mode',
      'nightlight',
      'nightlight round',
      'bedtime',
      'shield moon'
    ],
    'night': [
      'dark mode',
      'nightlight',
      'nightlight round',
      'bedtime',
      'nightlife'
    ],
    'weather': [
      'sunny',
      'cloudy',
      'cloud',
      'thunderstorm',
      'ac unit',
      'snowing',
      'tornado',
      'cyclone',
      'air',
      'thermostat'
    ],
    'storm': ['thunderstorm', 'tornado', 'cyclone', 'tsunami', 'flood'],
    'wind': ['air', 'wind power', 'tornado', 'cyclone'],
    'fire': ['whatshot', 'local fire department', 'outdoor grill'],
    'flame': ['whatshot', 'local fire department'],
    'leaf': ['eco', 'energy savings leaf', 'compost', 'spa'],
    'environment': [
      'eco',
      'recycling',
      'compost',
      'energy savings leaf',
      'solar power',
      'wind power',
      'park',
      'forest'
    ],

    // Sports synonyms
    'gym': [
      'fitness center',
      'self improvement',
      'directions run',
      'monitor weight'
    ],
    'exercise': [
      'fitness center',
      'directions run',
      'directions walk',
      'directions bike',
      'self improvement',
      'hiking'
    ],
    'workout': [
      'fitness center',
      'directions run',
      'self improvement',
      'monitor weight'
    ],
    'ball': [
      'sports soccer',
      'sports basketball',
      'sports baseball',
      'sports tennis',
      'sports volleyball',
      'sports football',
      'sports rugby',
      'sports cricket',
      'sports golf'
    ],
    'football': ['sports soccer', 'sports football'],
    'soccer': ['sports soccer'],
    'basketball': ['sports basketball'],
    'baseball': ['sports baseball'],
    'tennis': ['sports tennis'],
    'golf': ['sports golf'],
    'swim': ['pool', 'surfing', 'scuba diving'],
    'ski': ['downhill skiing', 'snowboarding'],
    'bike': [
      'directions bike',
      'pedal bike',
      'electric bike',
      'motorcycle',
      'two wheeler'
    ],
    'cycle': [
      'directions bike',
      'pedal bike',
      'electric bike',
      'cyclone',
      'loop',
      'recycling'
    ],
    'run': ['directions run', 'nordic walking', 'sports score'],
    'walk': ['directions walk', 'nordic walking', 'hiking'],
    'yoga': ['self improvement', 'spa', 'fitness center'],
    'meditation': ['self improvement', 'spa'],
    'martial': ['sports martial arts', 'sports kabaddi'],
    'race': ['sports motorsports', 'directions run', 'sports score', 'speed'],
    'climb': ['hiking', 'terrain', 'landscape'],

    // Health synonyms
    'doctor': [
      'medical services',
      'medical information',
      'local hospital',
      'healing',
      'vaccines'
    ],
    'nurse': ['medical services', 'local hospital', 'healing'],
    'hospital': [
      'local hospital',
      'medical services',
      'medical information',
      'healing',
      'emergency'
    ],
    'medicine': [
      'medication',
      'medication liquid',
      'local pharmacy',
      'vaccines',
      'healing'
    ],
    'pill': ['medication', 'medication liquid'],
    'health': [
      'health and safety',
      'medical services',
      'monitor heart',
      'healing',
      'spa',
      'self improvement'
    ],
    'weight': ['monitor weight', 'fitness center', 'scale'],
    'covid': ['coronavirus', 'masks', 'sanitizer', 'vaccines', 'sick'],
    'virus': ['coronavirus', 'sick', 'masks', 'bug report'],

    // Technology synonyms
    'pc': ['computer', 'desktop windows', 'desktop mac', 'laptop'],
    'mac': ['desktop mac', 'laptop mac', 'tablet mac'],
    'iphone': ['phone iphone', 'smartphone'],
    'android': ['phone android', 'smartphone'],
    'mobile': ['smartphone', 'phone android', 'phone iphone', 'tablet'],
    'ipad': ['tablet', 'tablet mac'],
    'program': [
      'code',
      'terminal',
      'developer board',
      'developer mode',
      'data object',
      'data array',
      'api'
    ],
    'develop': [
      'code',
      'terminal',
      'developer board',
      'developer mode',
      'api',
      'webhook',
      'bug report'
    ],
    'software': [
      'code',
      'terminal',
      'developer board',
      'api',
      'bug report',
      'webhook'
    ],
    'hack': ['code', 'terminal', 'bug report', 'security', 'vpn key'],
    'server': ['dns', 'storage', 'database', 'cloud upload', 'cloud download'],
    'internet': [
      'wifi',
      'public',
      'language',
      'cloud upload',
      'cloud download',
      'router',
      'link'
    ],
    'network': [
      'wifi',
      'router',
      'bluetooth',
      'nfc',
      'signal wifi 4 bar',
      'signal cellular alt',
      'hub',
      'lan'
    ],
    'wireless': ['wifi', 'bluetooth', 'nfc', 'signal wifi 4 bar', 'cast'],
    'battery': [
      'battery full',
      'battery charging full',
      'power',
      'electrical services'
    ],
    'charge': [
      'battery charging full',
      'power',
      'electrical services',
      'ev station',
      'bolt',
      'electric bolt'
    ],
    'scan': ['qr code', 'qr code scanner', 'scanner', 'fingerprint'],
    'print': ['print', 'local printshop', 'scanner'],

    // Shapes synonyms
    'shape': [
      'circle',
      'square',
      'rectangle',
      'hexagon',
      'pentagon',
      'diamond',
      'change history',
      'category',
      'interests'
    ],
    'triangle': ['change history'],
    'round': ['circle', 'panorama'],
    'sparkle': ['auto awesome', 'auto awesome mosaic', 'stars', 'flare'],
    'lightning': ['bolt', 'electric bolt', 'flash on'],
    'bright': [
      'brightness high',
      'brightness low',
      'light mode',
      'flare',
      'flash on',
      'sunny'
    ],
    'dark': [
      'dark mode',
      'nightlight',
      'bedtime',
      'nightlight round',
      'contrast'
    ],
    'hot': [
      'whatshot',
      'local fire department',
      'thermostat',
      'device thermostat'
    ],
    'warm': ['whatshot', 'sunny', 'thermostat'],
    'cool': ['ac unit', 'snowing', 'thermostat'],
    'biometric': ['fingerprint', 'face', 'security', 'lock'],

    // Objects & Tools synonyms
    'tool': [
      'construction',
      'build',
      'handyman',
      'plumbing',
      'carpenter',
      'hardware',
      'settings'
    ],
    'wrench': ['build', 'build circle', 'plumbing', 'settings'],
    'hammer': ['hardware', 'construction', 'handyman', 'carpenter', 'gavel'],
    'gear': ['settings', 'settings suggest', 'tune'],
    'config': ['settings', 'settings suggest', 'tune', 'admin panel settings'],
    'password': [
      'key',
      'lock',
      'vpn key',
      'password',
      'pin',
      'security',
      'shield'
    ],
    'secure': [
      'lock',
      'shield',
      'security',
      'verified',
      'verified user',
      'vpn key',
      'admin panel settings'
    ],
    'encrypt': [
      'lock',
      'key',
      'vpn key',
      'shield',
      'security',
      'enhanced encryption'
    ],
    'privacy': ['lock', 'security', 'shield', 'visibility off', 'vpn key'],
    'law': ['gavel', 'balance', 'policy', 'assignment'],
    'judge': ['gavel', 'balance'],
    'money': [
      'savings',
      'account balance wallet',
      'wallet',
      'payments',
      'credit card',
      'currency exchange',
      'price change',
      'local atm',
      'attach money'
    ],
    'cash': [
      'payments',
      'account balance wallet',
      'wallet',
      'local atm',
      'savings'
    ],
    'pay': [
      'payments',
      'credit card',
      'account balance wallet',
      'wallet',
      'currency exchange'
    ],
    'bank': [
      'account balance',
      'savings',
      'account balance wallet',
      'local atm'
    ],
    'shop': [
      'shopping cart',
      'shopping bag',
      'shopping basket',
      'add shopping cart',
      'storefront',
      'store',
      'local mall'
    ],
    'buy': [
      'shopping cart',
      'shopping bag',
      'shopping basket',
      'add shopping cart',
      'storefront',
      'store'
    ],
    'gift': ['redeem', 'card giftcard', 'celebration', 'cake'],
    'present': ['redeem', 'card giftcard', 'celebration'],
    'sale': ['sell', 'local offer', 'discount', 'percent', 'loyalty'],
    'deal': ['sell', 'local offer', 'discount', 'handshake', 'percent'],

    // Awards synonyms
    'trophy': ['emoji events', 'military tech', 'workspace premium'],
    'medal': ['military tech', 'workspace premium', 'emoji events'],
    'award': [
      'emoji events',
      'military tech',
      'workspace premium',
      'star',
      'stars'
    ],
    'winner': ['emoji events', 'sports score', 'star', 'workspace premium'],
    'party': ['celebration', 'party mode', 'cake', 'nightlife'],
    'birthday': [
      'cake',
      'celebration',
      'party mode',
      'card giftcard',
      'redeem'
    ],

    // Actions synonyms
    'pin': ['push pin', 'pin drop', 'location on', 'place', 'pin', 'bookmark'],
    'save': [
      'bookmark',
      'bookmarks',
      'bookmark add',
      'save',
      'save alt',
      'favorite'
    ],
    'tag': ['label', 'label important', 'tag', 'sell', 'local offer'],
    'idea': [
      'lightbulb',
      'lightbulb circle',
      'tips and updates',
      'emoji objects'
    ],
    'tip': ['tips and updates', 'lightbulb', 'info', 'help'],
    'danger': [
      'warning',
      'warning amber',
      'error',
      'report',
      'report problem',
      'priority high'
    ],
    'important': [
      'priority high',
      'notification important',
      'label important',
      'warning',
      'star',
      'flag'
    ],
    'ok': [
      'check circle',
      'check',
      'done',
      'done all',
      'task alt',
      'check circle outline'
    ],
    'yes': ['check circle', 'check', 'done', 'done all', 'thumb up'],
    'no': [
      'close',
      'cancel',
      'block',
      'do not disturb',
      'not interested',
      'remove circle',
      'thumb down'
    ],
    'stop': ['block', 'do not disturb', 'cancel', 'close', 'not interested'],
    'plus': ['add', 'add circle', 'add circle outline'],
    'minus': ['remove', 'remove circle'],

    // Religion synonyms
    'religion': [
      'church',
      'mosque',
      'temple hindu',
      'temple buddhist',
      'synagogue'
    ],
    'pray': [
      'church',
      'mosque',
      'temple hindu',
      'temple buddhist',
      'synagogue',
      'self improvement'
    ],
    'worship': [
      'church',
      'mosque',
      'temple hindu',
      'temple buddhist',
      'synagogue'
    ],
    'history': ['castle', 'fort', 'museum', 'history', 'history edu'],
    'heritage': ['castle', 'fort', 'museum', 'church'],

    // Home & Living synonyms
    'sleep': [
      'bed',
      'bedroom parent',
      'bedroom child',
      'bedtime',
      'nightlight',
      'hotel'
    ],
    'bedroom': ['bed', 'bedroom parent', 'bedroom child'],
    'bath': ['bathroom', 'bathtub', 'shower'],
    'furniture': [
      'chair',
      'chair alt',
      'table bar',
      'table restaurant',
      'bed',
      'living'
    ],
    'room': [
      'living',
      'bedroom parent',
      'bedroom child',
      'bathroom',
      'meeting room'
    ],
    'door': ['door back', 'door sliding', 'meeting room'],
    'outdoor': [
      'deck',
      'balcony',
      'yard',
      'fence',
      'garage',
      'park',
      'outdoor grill',
      'beach access'
    ],

    // Clothing synonyms
    'glasses': ['goggles'],
    'goggles': ['goggles', 'sports motorsports'],
    'clothes': ['checkroom', 'dry cleaning', 'iron', 'backpack'],
    'fashion': ['checkroom', 'dry cleaning', 'diamond', 'style'],
    'bag': ['backpack', 'luggage', 'shopping bag'],
    'suitcase': ['luggage', 'work', 'business center'],

    // Transport extras
    'taxi': ['local taxi', 'airport shuttle'],
    'fuel': ['local gas station', 'ev station'],
    'park': ['local parking', 'park', 'nature'],
    'ambulance': ['emergency', 'local hospital'],
    'police': ['local police', 'emergency', 'security'],

    // Misc
    'eye': ['visibility', 'visibility off', 'remove red eye', 'preview'],
    'see': ['visibility', 'preview', 'remove red eye'],
    'look': ['visibility', 'preview', 'search', 'zoom in', 'explore'],
    'find': ['search', 'zoom in', 'person search', 'explore', 'travel explore'],
    'magnify': ['search', 'zoom in', 'zoom out'],
    'trash': ['delete', 'delete forever', 'restore from trash'],
    'bin': ['delete', 'delete forever', 'restore from trash'],
    'erase': ['delete', 'delete forever', 'close', 'cancel'],
    'repeat': ['loop', 'replay', 'sync', 'refresh'],
    'reload': ['refresh', 'sync', 'replay'],
    'arrow': [
      'swap horiz',
      'swap vert',
      'compare arrows',
      'north',
      'south',
      'east',
      'west',
      'navigation'
    ],
    'external': ['open in new', 'launch', 'link', 'share', 'ios share'],
    'url': ['link', 'link off', 'open in new', 'launch'],
    'clipboard': [
      'content copy',
      'content paste',
      'content cut',
      'copy',
      'assignment'
    ],
    'fast': ['speed', 'bolt', 'flash on', 'rocket launch', 'directions run'],
    'slow': ['hourglass empty', 'hourglass full', 'snooze', 'timelapse'],
    'wait': [
      'hourglass empty',
      'hourglass full',
      'pending actions',
      'schedule',
      'timer'
    ],
    'temperature': ['thermostat', 'device thermostat', 'ac unit', 'whatshot'],
    'laundry': ['local laundry service', 'dry cleaning', 'iron'],
    'grocery': [
      'local grocery store',
      'local convenience store',
      'shopping cart',
      'shopping basket'
    ],
    'post': ['local post office', 'mail', 'email', 'send'],
    'measure': ['scale', 'straighten', 'square foot', 'aspect ratio'],
    'crop': ['crop', 'aspect ratio', 'photo filter'],
    'rotate': ['rotate left', 'rotate right', 'flip', 'transform'],
    'quote': ['format quote', 'notes', 'short text'],
    'write': ['edit', 'create', 'draw', 'border color', 'notes', 'note add'],
    'pen': ['edit', 'create', 'draw', 'border color'],
    'pencil': ['edit', 'create', 'draw', 'border color'],
    'color': [
      'palette',
      'colorize',
      'invert colors',
      'gradient',
      'format paint',
      'opacity'
    ],
  };

  /// Search icons by name and tags. Returns entries matching the query.
  static Map<String, IconData> search(String query) {
    if (query.isEmpty) return icons;
    final lower = query.toLowerCase();

    // Collect matching icon names from both direct name match and tag index
    final matchingNames = <String>{};

    // Direct name match
    for (final name in icons.keys) {
      if (name.contains(lower)) matchingNames.add(name);
    }

    // Tag index match
    for (final entry in _tagIndex.entries) {
      if (entry.key.contains(lower)) {
        matchingNames.addAll(entry.value);
      }
    }

    // Build result preserving original icon order
    return Map.fromEntries(
      icons.entries.where((e) => matchingNames.contains(e.key)),
    );
  }
}
